//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Delta.Logging.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_APP_ERRORS
    {
        public decimal ID { get; set; }
        public string LOG_UID { get; set; }
        public string APP_CODE { get; set; }
        public string LOG_CODE { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string DETAILS { get; set; }
        public string USER_ID { get; set; }
        public string USER_IP { get; set; }
        public string LOG_MESSAGE { get; set; }
        public string OBJ_ID { get; set; }
        public string ACTION { get; set; }
        public string FUNCTION { get; set; }
        public string MODULE { get; set; }
        public string LOG_LEVEL { get; set; }
    }
}
