//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Delta.Logging.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_APP_CODES
    {
        public string APP_CODE { get; set; }
        public string DESCR { get; set; }
    }
}
