//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3625
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.OracleDb.OracleObjects
{
    using System;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    using SendMail.Model.ComunicazioniMapping;
    using SendMail.Model;
    using OracleTypes = global::Oracle.DataAccess.Types;
    using OracleClient = global::Oracle.DataAccess.Client;

    public class ComAllegatoType : ComAllegato, OracleTypes.INullable, OracleTypes.IOracleCustomType, IXmlSerializable
    {
        #region "Private Fields"
        private bool m_IsNull;

        private bool m_ID_ALLEGATOIsNull;

        private bool m_REF_ID_COMIsNull;

        private long m_ID_ALLEGATO;

        private string m_ALLEGATO_NAME;

        private byte[] m_ALLEGATO_FILE;

        private string m_ALLEGATO_EXT;

        private long m_REF_ID_COM;

        private string m_FLG_PROT_TO_UPL;

        private string m_ALLEGATO_TPU;

        private string m_FLG_INS_PROT;
        #endregion

        #region "C.tor"
        public ComAllegatoType()
        {
            // TODO : Add code to initialise the object
            this.m_ID_ALLEGATOIsNull = true;
            this.m_REF_ID_COMIsNull = true;
        }

        public ComAllegatoType(string str)
        {
            // TODO : Add code to initialise the object based on the given string 
        }

        public ComAllegatoType(ComAllegato a)
            : base(a)
        {
            if (a == null || a.IsValid == false)
            {
                this.m_IsNull = true;
                return;
            }

            this.m_ID_ALLEGATOIsNull = !a.IdAllegato.HasValue;
            this.m_REF_ID_COMIsNull = !a.RefIdCom.HasValue;

            if (a.FlgProtToUpl == AllegatoProtocolloStatus.UNKNOWN)
            {
                this.m_FLG_PROT_TO_UPL = ((int)AllegatoProtocolloStatus.FALSE).ToString();
            }
            else
            {
                this.m_FLG_PROT_TO_UPL = ((int)a.FlgProtToUpl).ToString();
            }

            if (a.FlgInsProt == AllegatoProtocolloStatus.UNKNOWN)
            {
                this.m_FLG_INS_PROT = ((int)AllegatoProtocolloStatus.FALSE).ToString();
            }
            else
            {
                this.m_FLG_INS_PROT = ((int)a.FlgInsProt).ToString();
            }
        }
        #endregion

        #region "Public Fields"
        public virtual bool IsNull
        {
            get
            {
                return this.m_IsNull;
            }
        }

        public static ComAllegatoType Null
        {
            get
            {
                ComAllegatoType obj = new ComAllegatoType();
                obj.m_IsNull = true;
                return obj;
            }
        }

        public bool ID_ALLEGATOIsNull
        {
            get
            {
                return this.m_ID_ALLEGATOIsNull;
            }
            set
            {
                this.m_ID_ALLEGATOIsNull = value;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("ID_ALLEGATO")]
        public override long? IdAllegato
        {
            get
            {
                if (this.ID_ALLEGATOIsNull == true)
                    return null;
                return this.m_ID_ALLEGATO;
            }
            set
            {
                this.m_ID_ALLEGATOIsNull = !(value.HasValue);
                if (value.HasValue)
                    this.m_ID_ALLEGATO = (long)value;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("ALLEGATO_NAME")]
        public override string AllegatoName
        {
            get
            {
                return this.m_ALLEGATO_NAME;
            }
            set
            {
                this.m_ALLEGATO_NAME = value;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("ALLEGATO_FILE")]
        public override byte[] AllegatoFile
        {
            get
            {
                return this.m_ALLEGATO_FILE;
            }
            set
            {
                this.m_ALLEGATO_FILE = value;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("ALLEGATO_EXT")]
        public override string AllegatoExt
        {
            get
            {
                return this.m_ALLEGATO_EXT;
            }
            set
            {
                this.m_ALLEGATO_EXT = value;
            }
        }

        public bool REF_ID_COMIsNull
        {
            get
            {
                return this.m_REF_ID_COMIsNull;
            }
            set
            {
                this.m_REF_ID_COMIsNull = value;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("REF_ID_COM")]
        public override long? RefIdCom
        {
            get
            {
                if (this.REF_ID_COMIsNull == true)
                    return null;
                return this.m_REF_ID_COM;
            }
            set
            {
                this.REF_ID_COMIsNull = !(value.HasValue);
                if (value.HasValue)
                    this.m_REF_ID_COM = (long)value;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("FLG_PROT_TO_UPL")]
        public string FLG_PROT_TO_UPL
        {
            get
            {
                return this.m_FLG_PROT_TO_UPL;
            }
            set
            {
                this.m_FLG_PROT_TO_UPL = value;
                //set della proprietà della classe base
                AllegatoProtocolloStatus protToUpl = AllegatoProtocolloStatus.UNKNOWN;
                int pStat;
                if (!String.IsNullOrEmpty(value) &&
                    int.TryParse(value, out pStat) &&
                    Enum.IsDefined(typeof(AllegatoProtocolloStatus), pStat))
                {
                    protToUpl = (AllegatoProtocolloStatus)pStat;
                }
                base.FlgProtToUpl = protToUpl;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("ALLEGATO_TPU")]
        public override string AllegatoTpu
        {
            get
            {
                return this.m_ALLEGATO_TPU;
            }
            set
            {
                this.m_ALLEGATO_TPU = value;
            }
        }

        [OracleTypes.OracleObjectMappingAttribute("FLG_INS_PROT")]
        public string FLG_INS_PROT
        {
            get
            {
                return this.m_FLG_INS_PROT;
            }
            set
            {
                this.m_FLG_INS_PROT = value;

                AllegatoProtocolloStatus insProt = AllegatoProtocolloStatus.UNKNOWN;
                int pStat;
                if (!String.IsNullOrEmpty(value) &&
                    int.TryParse(value, out pStat) &&
                    Enum.IsDefined(typeof(AllegatoProtocolloStatus), pStat))
                {
                    insProt = (AllegatoProtocolloStatus)pStat;
                }
                base.FlgInsProt = insProt;
            }
        }
        #endregion

        #region "Public Methods"
        public virtual void FromCustomObject(OracleClient.OracleConnection con, System.IntPtr pUdt)
        {
            if ((ID_ALLEGATOIsNull == false))
            {
                OracleTypes.OracleUdt.SetValue(con, pUdt, "ID_ALLEGATO", this.IdAllegato);
            }
            OracleTypes.OracleUdt.SetValue(con, pUdt, "ALLEGATO_NAME", this.AllegatoName);
            OracleTypes.OracleUdt.SetValue(con, pUdt, "ALLEGATO_FILE", this.AllegatoFile);
            OracleTypes.OracleUdt.SetValue(con, pUdt, "ALLEGATO_EXT", this.AllegatoExt);
            if ((REF_ID_COMIsNull == false))
            {
                OracleTypes.OracleUdt.SetValue(con, pUdt, "REF_ID_COM", this.RefIdCom);
            }
            OracleTypes.OracleUdt.SetValue(con, pUdt, "FLG_PROT_TO_UPL", this.FLG_PROT_TO_UPL);
            OracleTypes.OracleUdt.SetValue(con, pUdt, "ALLEGATO_TPU", this.AllegatoTpu);
            OracleTypes.OracleUdt.SetValue(con, pUdt, "FLG_INS_PROT", this.FLG_INS_PROT);
        }

        public virtual void ToCustomObject(OracleClient.OracleConnection con, System.IntPtr pUdt)
        {
            this.ID_ALLEGATOIsNull = OracleTypes.OracleUdt.IsDBNull(con, pUdt, "ID_ALLEGATO");
            if ((ID_ALLEGATOIsNull == false))
            {
                this.IdAllegato = ((long)(OracleTypes.OracleUdt.GetValue(con, pUdt, "ID_ALLEGATO")));
                //this.oID_ALLEGATO = ((long)(Oracle.DataAccess.Types.OracleUdt.GetValue(con, pUdt, "ID_ALLEGATO")));
            }
            this.AllegatoName = ((string)(OracleTypes.OracleUdt.GetValue(con, pUdt, "ALLEGATO_NAME")));
            this.AllegatoFile = ((byte[])(OracleTypes.OracleUdt.GetValue(con, pUdt, "ALLEGATO_FILE")));
            this.AllegatoExt = ((string)(OracleTypes.OracleUdt.GetValue(con, pUdt, "ALLEGATO_EXT")));
            this.REF_ID_COMIsNull = OracleTypes.OracleUdt.IsDBNull(con, pUdt, "REF_ID_COM");
            if ((REF_ID_COMIsNull == false))
            {
                this.RefIdCom = ((long)(OracleTypes.OracleUdt.GetValue(con, pUdt, "REF_ID_COM")));
            }
            this.FLG_PROT_TO_UPL = ((string)(OracleTypes.OracleUdt.GetValue(con, pUdt, "FLG_PROT_TO_UPL")));
            this.AllegatoTpu = ((string)(OracleTypes.OracleUdt.GetValue(con, pUdt, "ALLEGATO_TPU")));
            this.FLG_INS_PROT = ((string)(OracleTypes.OracleUdt.GetValue(con, pUdt, "FLG_INS_PROT")));
        }

        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            // TODO : Read Serialized Xml Data
        }

        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            // TODO : Serialize object to xml data
        }

        public virtual XmlSchema GetSchema()
        {
            // TODO : Implement GetSchema
            return null;
        }

        public override string ToString()
        {
            // TODO : Return a string that represents the current object
            return "";
        }

        public static ComAllegatoType Parse(string str)
        {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new ComAllegatoType();
        }
        #endregion

        #region "Commentato"
        /*
        [OracleObjectMappingAttribute("ID_ALLEGATO")]
        public long oID_ALLEGATO
        {
            get
            {
                return this.m_ID_ALLEGATO;
            }
            set
            {
                this.m_ID_ALLEGATO = value;
            }
        }

        [OracleObjectMappingAttribute("ALLEGATO_NAME")]
        public string oALLEGATO_NAME
        {
            get
            {
                return this.m_ALLEGATO_NAME;
            }
            set
            {
                this.m_ALLEGATO_NAME = value;
            }
        }

        [OracleObjectMappingAttribute("ALLEGATO_FILE")]
        public byte[] oALLEGATO_FILE
        {
            get
            {
                return this.m_ALLEGATO_FILE;
            }
            set
            {
                this.m_ALLEGATO_FILE = value;
            }
        }

        [OracleObjectMappingAttribute("ALLEGATO_EXT")]
        public string oALLEGATO_EXT
        {
            get
            {
                return this.m_ALLEGATO_EXT;
            }
            set
            {
                this.m_ALLEGATO_EXT = value;
            }
        }

        [OracleObjectMappingAttribute("REF_ID_COM")]
        public long oREF_ID_COM
        {
            get
            {
                return this.m_REF_ID_COM;
            }
            set
            {
                this.m_REF_ID_COM = value;
            }
        }

        [OracleObjectMappingAttribute("FLG_PROT_TO_UPL")]
        public string oFLG_PROT_TO_UPL
        {
            get
            {
                return this.m_FLG_PROT_TO_UPL;
            }
            set
            {
                this.m_FLG_PROT_TO_UPL = value;
            }
        }

        [OracleObjectMappingAttribute("ALLEGATO_TPU")]
        public string oALLEGATO_TPU
        {
            get
            {
                return this.m_ALLEGATO_TPU;
            }
            set
            {
                this.m_ALLEGATO_TPU = value;
            }
        }

        [OracleObjectMappingAttribute("FLG_INS_PROT")]
        public string oFLG_INS_PROT
        {
            get
            {
                return this.m_FLG_INS_PROT;
            }
            set
            {
                this.m_FLG_INS_PROT = value;
            }
        }
        */
        #endregion
    }

    // Factory to create an object for the above class
    [OracleTypes.OracleCustomTypeMappingAttribute("COM_ALLEGATO_TYPE")]
    public class ComAllegatoTypeFactory : OracleTypes.IOracleCustomTypeFactory
    {

        public virtual OracleTypes.IOracleCustomType CreateObject()
        {
            ComAllegatoType obj = new ComAllegatoType();
            return obj;
        }
    }
}
