//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3625
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.OracleDb.OracleObjects
{
    using System;
    using System.Xml.Serialization;
    using System.Xml.Schema;
    using OracleClient = global::Oracle.DataAccess.Client;
    using OracleTypes = global::Oracle.DataAccess.Types;

    public class ComFlussoListType : OracleTypes.INullable, OracleTypes.IOracleCustomType, IXmlSerializable
    {

        private bool m_IsNull;

        private ComFlussoType[] m_COM_FLUSSO_TYPE;

        public ComFlussoListType()
        {
            // TODO : Add code to initialise the object
        }

        public ComFlussoListType(string str)
        {
            // TODO : Add code to initialise the object based on the given string 
        }

        public virtual bool IsNull
        {
            get
            {
                return this.m_IsNull;
            }
        }

        public static ComFlussoListType Null
        {
            get
            {
                ComFlussoListType obj = new ComFlussoListType();
                obj.m_IsNull = true;
                return obj;
            }
        }

        [OracleTypes.OracleArrayMappingAttribute()]
        public virtual ComFlussoType[] ComFlusso
        {
            get
            {
                return this.m_COM_FLUSSO_TYPE;
            }
            set
            {
                this.m_COM_FLUSSO_TYPE = value;
            }
        }

        public virtual void FromCustomObject(OracleClient.OracleConnection con, System.IntPtr pUdt)
        {
            OracleTypes.OracleUdt.SetValue(con, pUdt, 0, this.m_COM_FLUSSO_TYPE);
        }

        public virtual void ToCustomObject(OracleClient.OracleConnection con, System.IntPtr pUdt)
        {
            this.m_COM_FLUSSO_TYPE = ((ComFlussoType[])(OracleTypes.OracleUdt.GetValue(con, pUdt, 0)));
        }

        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            // TODO : Read Serialized Xml Data
        }

        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            // TODO : Serialize object to xml data
        }

        public virtual XmlSchema GetSchema()
        {
            // TODO : Implement GetSchema
            return null;
        }

        public override string ToString()
        {
            // TODO : Return a string that represents the current object
            return "";
        }

        public static ComFlussoListType Parse(string str)
        {
            // TODO : Add code needed to parse the string and get the object represented by the string
            return new ComFlussoListType();
        }
    }

    // Factory to create an object for the above class
    [OracleTypes.OracleCustomTypeMappingAttribute("COM_FLUSSO_LIST_TYPE")]
    public class ComFlussoListTypeFactory : OracleTypes.IOracleCustomTypeFactory, OracleTypes.IOracleArrayTypeFactory
    {

        public virtual OracleTypes.IOracleCustomType CreateObject()
        {
            ComFlussoListType obj = new ComFlussoListType();
            return obj;
        }

        public virtual System.Array CreateArray(int length)
        {
            ComFlussoType[] collElem = new ComFlussoType[length];
            return collElem;
        }

        public virtual System.Array CreateStatusArray(int length)
        {
            return null;
        }
    }
}
