//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONS_FOLDERS
    {
        public double ID { get; set; }
        public double IDFOLDER { get; set; }
        public double IDACTION { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual ACTIONS ACTIONS { get; set; }
    }
}
