//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNICAZIONI_TITOLI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMUNICAZIONI_TITOLI()
        {
            this.COMUNICAZIONI_SOTTOTITOLI = new HashSet<COMUNICAZIONI_SOTTOTITOLI>();
            this.RUBR_CONTATTI_BACKEND = new HashSet<RUBR_CONTATTI_BACKEND>();
            this.MAIL_SENDERS = new HashSet<MAIL_SENDERS>();
        }
    
        public decimal ID_TITOLO { get; set; }
        public string APP_CODE { get; set; }
        public string PROT_CODE { get; set; }
        public string TITOLO { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public string NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMUNICAZIONI_SOTTOTITOLI> COMUNICAZIONI_SOTTOTITOLI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUBR_CONTATTI_BACKEND> RUBR_CONTATTI_BACKEND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAIL_SENDERS> MAIL_SENDERS { get; set; }
    }
}
