//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNICAZIONI_PROTOCOLLO_XML
    {
        public decimal REF_ID_COM { get; set; }
        public string PROT_XML { get; set; }
    
        public virtual COMUNICAZIONI COMUNICAZIONI { get; set; }
    }
}
