//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNICAZIONI_PROTOCOLLO
    {
        public decimal REF_ID_COM { get; set; }
        public string REQ_PROT_TIPO { get; set; }
        public string REQ_COD_DOCUMENTO { get; set; }
        public Nullable<decimal> REQ_IS_ESISTENTE { get; set; }
        public Nullable<decimal> REQ_IS_RISERVATO { get; set; }
        public string REQ_SUBJECT { get; set; }
        public string RESP_PROT_TIPO { get; set; }
        public Nullable<decimal> RESP_PROT_ANNO { get; set; }
        public string RESP_PROT_NUMERO { get; set; }
        public string PROT_IN_OUT { get; set; }
    
        public virtual COMUNICAZIONI COMUNICAZIONI { get; set; }
    }
}
