//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNICAZIONI_DESTINATARI_PROT
    {
        public decimal REF_ID_COM { get; set; }
        public string CODICE_FISCALE { get; set; }
        public Nullable<System.DateTime> DATA_NAS { get; set; }
        public string DESCR_NOMINATIVO { get; set; }
        public Nullable<decimal> INTERESSATO { get; set; }
        public string TIPO_PERSONA { get; set; }
        public string CODICE_RESPONSABILE_STRUTTURA { get; set; }
        public string CODICE_STRUTTURA { get; set; }
        public decimal ID_DEST { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
