//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNICAZIONI_ALLEGATI
    {
        public decimal ID_ALLEGATO { get; set; }
        public decimal REF_ID_COM { get; set; }
        public string ALLEGATO_TPU { get; set; }
        public byte[] ALLEGATO_FILE { get; set; }
        public string ALLEGATO_EXT { get; set; }
        public string FLG_INS_PROT { get; set; }
        public string FLG_PROT_TO_UPL { get; set; }
        public string ALLEGATO_NAME { get; set; }
        public decimal DA_LAVORARE { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual COMUNICAZIONI COMUNICAZIONI { get; set; }
    }
}
