//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FAXPECContext : DbContext
    {
        public FAXPECContext()
            : base("name=FAXPECContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIONS> ACTIONS { get; set; }
        public virtual DbSet<ACTIONS_FOLDERS> ACTIONS_FOLDERS { get; set; }
        public virtual DbSet<COMUNICAZIONI> COMUNICAZIONI { get; set; }
        public virtual DbSet<COMUNICAZIONI_ALLEGATI> COMUNICAZIONI_ALLEGATI { get; set; }
        public virtual DbSet<COMUNICAZIONI_CANALI> COMUNICAZIONI_CANALI { get; set; }
        public virtual DbSet<COMUNICAZIONI_DESTINATARI> COMUNICAZIONI_DESTINATARI { get; set; }
        public virtual DbSet<COMUNICAZIONI_ENTITA_USED> COMUNICAZIONI_ENTITA_USED { get; set; }
        public virtual DbSet<COMUNICAZIONI_FLUSSO> COMUNICAZIONI_FLUSSO { get; set; }
        public virtual DbSet<COMUNICAZIONI_FLUSSO_PROT> COMUNICAZIONI_FLUSSO_PROT { get; set; }
        public virtual DbSet<COMUNICAZIONI_PROTOCOLLO> COMUNICAZIONI_PROTOCOLLO { get; set; }
        public virtual DbSet<COMUNICAZIONI_SOTTOTITOLI> COMUNICAZIONI_SOTTOTITOLI { get; set; }
        public virtual DbSet<COMUNICAZIONI_TITOLI> COMUNICAZIONI_TITOLI { get; set; }
        public virtual DbSet<FOLDERS> FOLDERS { get; set; }
        public virtual DbSet<FOLDERS_SENDERS> FOLDERS_SENDERS { get; set; }
        public virtual DbSet<MAIL_CONTENT> MAIL_CONTENT { get; set; }
        public virtual DbSet<MAIL_INBOX> MAIL_INBOX { get; set; }
        public virtual DbSet<MAIL_INBOX_FLUSSO> MAIL_INBOX_FLUSSO { get; set; }
        public virtual DbSet<MAIL_REFS_NEW> MAIL_REFS_NEW { get; set; }
        public virtual DbSet<MAIL_SENDERS> MAIL_SENDERS { get; set; }
        public virtual DbSet<MAIL_USERS_ADMIN_BACKEND> MAIL_USERS_ADMIN_BACKEND { get; set; }
        public virtual DbSet<MAIL_USERS_BACKEND> MAIL_USERS_BACKEND { get; set; }
        public virtual DbSet<MAIL_USERS_SENDER_BACKEND> MAIL_USERS_SENDER_BACKEND { get; set; }
        public virtual DbSet<MAILSERVERS> MAILSERVERS { get; set; }
        public virtual DbSet<RUBR_ADDRESS> RUBR_ADDRESS { get; set; }
        public virtual DbSet<RUBR_BACKEND> RUBR_BACKEND { get; set; }
        public virtual DbSet<RUBR_CONTATTI> RUBR_CONTATTI { get; set; }
        public virtual DbSet<RUBR_CONTATTI_BACKEND> RUBR_CONTATTI_BACKEND { get; set; }
        public virtual DbSet<RUBR_ENTITA> RUBR_ENTITA { get; set; }
        public virtual DbSet<RUBR_ENTITA_USED> RUBR_ENTITA_USED { get; set; }
        public virtual DbSet<RUBR_MAPPING_PROTOCOLLO> RUBR_MAPPING_PROTOCOLLO { get; set; }
        public virtual DbSet<RUBR_REFERRAL_TYPE> RUBR_REFERRAL_TYPE { get; set; }
        public virtual DbSet<RUBR_TAGS> RUBR_TAGS { get; set; }
        public virtual DbSet<V_MAP_APPL_CONTATTI_NEW> V_MAP_APPL_CONTATTI_NEW { get; set; }
        public virtual DbSet<V_RUBR_CONTATTI> V_RUBR_CONTATTI { get; set; }
    }
}
