//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FOLDERS_SENDERS
    {
        public double ID { get; set; }
        public decimal IDFOLDER { get; set; }
        public decimal IDSENDER { get; set; }
    
        public virtual FOLDERS FOLDERS { get; set; }
        public virtual MAIL_SENDERS MAIL_SENDERS { get; set; }
    }
}
