//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ACTIONS
    {
        public decimal ID { get; set; }
        public string LOG_UID { get; set; }
        public string APP_CODE { get; set; }
        public string LOG_CODE { get; set; }
        public string USER_ID { get; set; }
        public string USER_MAIL { get; set; }
        public string LOG_DETAILS { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string LOG_LEVEL { get; set; }
        public string OBJECT_ID { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
