//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_REFS
    {
        public decimal ID_REF { get; set; }
        public decimal REF_ID_MAIL { get; set; }
        public string MAIL_DESTINATARIO { get; set; }
        public string TIPO_REF { get; set; }
        public Nullable<decimal> REF_ID_COM_DEST { get; set; }
        public System.Guid ROWID { get; set; }
    
        public virtual COMUNICAZIONI_DESTINATARI COMUNICAZIONI_DESTINATARI { get; set; }
        public virtual MAIL_CONTENT MAIL_CONTENT { get; set; }
    }
}
