//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILSERVERS
    {
        public double ID_SVR { get; set; }
        public string NOME { get; set; }
        public string INDIRIZZO_IN { get; set; }
        public string PROTOCOLLO_IN { get; set; }
        public string PORTA_IN { get; set; }
        public string SSL_IN { get; set; }
        public string INDIRIZZO_OUT { get; set; }
        public string PORTA_OUT { get; set; }
        public string SSL_OUT { get; set; }
        public string AUTH_OUT { get; set; }
        public string DOMINUS { get; set; }
        public string FLG_ISPEC { get; set; }
    }
}
