//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_CONTENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAIL_CONTENT()
        {
            this.MAIL_REFS_NEW = new HashSet<MAIL_REFS_NEW>();
        }
    
        public decimal ID_MAIL { get; set; }
        public decimal REF_ID_COM { get; set; }
        public string MAIL_SENDER { get; set; }
        public string MAIL_SUBJECT { get; set; }
        public string MAIL_TEXT { get; set; }
        public string FLG_ANNULLAMENTO { get; set; }
        public string FLG_CUSTOM_REFS { get; set; }
        public Nullable<decimal> FOLLOWS { get; set; }
        public decimal FOLDERID { get; set; }
        public string FOLDERTIPO { get; set; }
        public Nullable<decimal> REF_ID_SENDER { get; set; }
        public Nullable<double> REF_ID_FLUSSO_ATTUALE { get; set; }
        public Nullable<double> REF_ID_FLUSSO_INSERIMENTO { get; set; }
    
        public virtual COMUNICAZIONI COMUNICAZIONI { get; set; }
        public virtual COMUNICAZIONI_FLUSSO COMUNICAZIONI_FLUSSO { get; set; }
        public virtual COMUNICAZIONI_FLUSSO COMUNICAZIONI_FLUSSO1 { get; set; }
        public virtual FOLDERS FOLDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAIL_REFS_NEW> MAIL_REFS_NEW { get; set; }
    }
}
