//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL_SENDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAIL_SENDERS()
        {
            this.FOLDERS_SENDERS = new HashSet<FOLDERS_SENDERS>();
            this.MAIL_USERS_SENDER_BACKEND = new HashSet<MAIL_USERS_SENDER_BACKEND>();
            this.COMUNICAZIONI_TITOLI = new HashSet<COMUNICAZIONI_TITOLI>();
        }
    
        public decimal ID_SENDER { get; set; }
        public string MAIL { get; set; }
        public decimal ID_MAILSERVER { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<decimal> ID_RESPONSABILE { get; set; }
        public string FLG_MANAGED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOLDERS_SENDERS> FOLDERS_SENDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAIL_USERS_SENDER_BACKEND> MAIL_USERS_SENDER_BACKEND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMUNICAZIONI_TITOLI> COMUNICAZIONI_TITOLI { get; set; }
    }
}
