//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBR_ENTITA_USED
    {
        public decimal ID_ENT_USED { get; set; }
        public string MAIL { get; set; }
        public string FAX { get; set; }
        public string TELEFONO { get; set; }
        public string CONTACT_REF { get; set; }
        public string REFERRAL_TYPE { get; set; }
        public string COGNOME { get; set; }
        public string NOME { get; set; }
        public string COD_FIS { get; set; }
        public string P_IVA { get; set; }
        public string RAGIONE_SOCIALE { get; set; }
        public string UFFICIO { get; set; }
        public string NOTE { get; set; }
        public string INDIRIZZO { get; set; }
        public string CIVICO { get; set; }
        public string CAP { get; set; }
        public string COMUNE { get; set; }
        public string SIGLA_PROV { get; set; }
        public string COD_ISO_STATO { get; set; }
        public Nullable<decimal> ID_REFERRAL { get; set; }
    }
}
