//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBR_MAPPING_PROTOCOLLO
    {
        public string COD_APPL { get; set; }
        public string COD_ID { get; set; }
        public string STR_ORG { get; set; }
        public string COD_UTE_RSP { get; set; }
        public decimal ID { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
