//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBR_ADDRESS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RUBR_ADDRESS()
        {
            this.RUBR_ENTITA = new HashSet<RUBR_ENTITA>();
        }
    
        public decimal ID_ADDRESS { get; set; }
        public string INDIRIZZO { get; set; }
        public string CIVICO { get; set; }
        public string CAP { get; set; }
        public string COMUNE { get; set; }
        public string SIGLA_PROV { get; set; }
        public string COD_ISO_STATO { get; set; }
        public string FLG_IPA { get; set; }
        public string INDIRIZZO_NON_STANDARD { get; set; }
        public Nullable<decimal> AFF_IPA { get; set; }
        public System.Guid ROWID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RUBR_ENTITA> RUBR_ENTITA { get; set; }
    }
}
