//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RUBR_STATI
    {
        public string COD_ISO { get; set; }
        public string DESCR_ISO { get; set; }
        public string COD_ISTAT { get; set; }
        public string DESCR_STATO { get; set; }
        public string FLG_VAL { get; set; }
    }
}
