//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERRIT_NAZIONI
    {
        public decimal STATO_ID { get; set; }
        public string DENOMINAZIONE { get; set; }
        public string COD_ISTAT { get; set; }
        public string COD_ISO { get; set; }
        public string DENOMINAZIONE_ISO { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
