//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CONTATTI_RUBR_AND_IPA
    {
        public string SRC { get; set; }
        public double MAIL_ID { get; set; }
        public string MAIL { get; set; }
        public string TEL { get; set; }
        public string FAX { get; set; }
        public decimal ID_REFERRAL { get; set; }
        public Nullable<decimal> ID_PADRE { get; set; }
        public string REFERRAL_TYPE { get; set; }
        public string COGNOME { get; set; }
        public string NOME { get; set; }
        public string COD_FIS { get; set; }
        public string P_IVA { get; set; }
        public string RAGIONE_SOCIALE { get; set; }
        public string UFFICIO { get; set; }
        public string NOTE { get; set; }
        public Nullable<decimal> REF_ID_ADDRESS { get; set; }
        public string FLG_IPA { get; set; }
        public string IPA_DN { get; set; }
        public string IPA_ID { get; set; }
        public string DISAMB_PRE { get; set; }
        public string DISAMB_POST { get; set; }
        public Nullable<decimal> REF_ORG { get; set; }
        public string SITO_WEB { get; set; }
        public Nullable<decimal> AFF_IPA { get; set; }
        public string INDIRIZZO { get; set; }
        public string CIVICO { get; set; }
        public string CAP { get; set; }
        public string COMUNE { get; set; }
        public string SIGLA_PROV { get; set; }
        public string COD_ISO_STATO { get; set; }
        public string DESCR_ISO { get; set; }
        public string INDIRIZZO_NON_STANDARD { get; set; }
    }
}
