//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail.Data.SQLServerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_COMUNICAZIONI_COMPLETE
    {
        public decimal ID_COM { get; set; }
        public decimal REF_ID_SOTTOTITOLO { get; set; }
        public string FLG_NOTIFICA { get; set; }
        public string MAIL_NOTIFICA { get; set; }
        public string UTE_INS { get; set; }
        public string COD_APP_INS { get; set; }
        public string ORIG_UID { get; set; }
        public decimal AZ_PROT { get; set; }
        public decimal IN_OUT { get; set; }
        public string APP_CODE { get; set; }
        public string TITOLO { get; set; }
        public string NOTE_TIT { get; set; }
        public string SOTTOTITOLO { get; set; }
        public string COM_CODE { get; set; }
        public string NOTE_SOT { get; set; }
        public string STATO_COMUNICAZIONE_OLD { get; set; }
        public string STATO_COMUNICAZIONE_NEW { get; set; }
        public System.DateTime DATA_OPERAZIONE { get; set; }
        public string UTE_OPE { get; set; }
        public string CANALE { get; set; }
        public Nullable<decimal> ID_ENT_USED { get; set; }
        public string MAIL { get; set; }
        public string FAX { get; set; }
        public string TELEFONO { get; set; }
        public string CONTACT_REF { get; set; }
        public string REFERRAL_TYPE { get; set; }
        public string COGNOME { get; set; }
        public string NOME { get; set; }
        public string COD_FIS { get; set; }
        public string P_IVA { get; set; }
        public string RAGIONE_SOCIALE { get; set; }
        public string UFFICIO { get; set; }
        public string NOTE_RUB { get; set; }
        public string INDIRIZZO { get; set; }
        public string CIVICO { get; set; }
        public string CAP { get; set; }
        public string COMUNE { get; set; }
        public string SIGLA_PROV { get; set; }
        public string COD_ISO_STATO { get; set; }
        public Nullable<decimal> ID_REFERRAL { get; set; }
        public Nullable<decimal> ID_MAIL { get; set; }
        public string MAIL_SENDER { get; set; }
        public string MAIL_SUBJECT { get; set; }
        public string MAIL_TEXT { get; set; }
        public string FLG_ANNULLAMENTO { get; set; }
        public string FLG_CUSTOM_REFS { get; set; }
        public Nullable<decimal> FOLLOWS { get; set; }
        public string ALLEGATO_TPU { get; set; }
        public string ALLEGATO_EXT { get; set; }
        public string FLG_INS_PROT { get; set; }
        public string FLG_PROT_TO_UPL { get; set; }
        public string ALLEGATO_NAME { get; set; }
    }
}
