//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da uno strumento.
//
//     Le modifiche a questo file possono causare un comportamento non corretto e verranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionePEC.pages.MailClient
{


    public partial class MailBoxInBox
    {
    }
}
