WITH M_CON AS (SELECT REF_ID_COM, ROW_NUMBER() OVER (ORDER BY REF_ID_COM DESC) AS RN 
FROM [FAXPEC].[FAXPEC].[MAIL_CONTENT] MC WHERE MAIL_SENDER = 'n.ruberto@deltamanagement.it' 
AND FOLDERTIPO='O' AND FOLDERID=2) SELECT convert(varchar,MC.ID_MAIL) AS "MAIL_ID", MC.MAIL_SENDER AS "MAIL_FROM",
 MC.MAIL_SUBJECT, SUBSTRING(MC.MAIL_TEXT, 1 ,150) as "MAIL_TEXT", FOLDERID , 
 FOLDERTIPO , R."MAIL_TO", '' as "MAIL_CC", '' as "MAIL_CCN", FL.STATO_COMUNICAZIONE_NEW 
  AS "STATUS_MAIL", FL1.DATA_OPERAZIONE  AS "DATA_INVIO", (SELECT MAX(DATA_OPERAZIONE)
   FROM FAXPEC.COMUNICAZIONI_FLUSSO 
   WHERE REF_ID_COM = MC.REF_ID_COM AND STATO_COMUNICAZIONE_NEW 
   IN 
   ('28', '29')) AS "DATA_RICEZIONE", MC.FLG_ANNULLAMENTO AS "STATUS_SERVER", NULL as "FLG_RATING",
    IIF(((SELECT COUNT(*) FROM [FAXPEC].[FAXPEC].[COMUNICAZIONI_ALLEGATI] al  
	WHERE
	 al.REF_ID_COM = MC.REF_ID_COM) = 0), '0', '1') AS "FLG_ATTACHMENTS",
	  (SELECT UTE_OPE FROM [FAXPEC].[FAXPEC].[COMUNICAZIONI_FLUSSO] fu 
	   WHERE fu.REF_ID_COM = MC.REF_ID_COM AND 
	  STATO_COMUNICAZIONE_NEW = '20') AS "UTENTE" ,0 AS MSG_LENGTH  FROM 
	  [FAXPEC].[FAXPEC].[MAIL_CONTENT] MC LEFT OUTER JOIN [FAXPEC].[FAXPEC].[COMUNICAZIONI_FLUSSO] FL ON 
	   MC.REF_ID_FLUSSO_ATTUALE=FL.ID_FLUSSO  LEFT OUTER JOIN [FAXPEC].[FAXPEC].[COMUNICAZIONI_FLUSSO] FL1
	    ON MC.REF_ID_FLUSSO_INSERIMENTO=FL1.ID_FLUSSO  LEFT OUTER JOIN
		 (SELECT 
		REF_ID_MAIL, MAIL_DESTINATARIO AS "MAIL_TO"  FROM [FAXPEC].MAIL_REFS_NEW
	) R ON MC.ID_MAIL = R.REF_ID_MAIL WHERE MAIL_SENDER = 'n.ruberto@deltamanagement.it' 
		 AND FOLDERTIPO='O' AND FOLDERID=2 AND MC.REF_ID_COM  IN (SELECT REF_ID_COM FROM 
M_CON WHERE RN BETWEEN 1 AND 25) 
ORDER BY DATA_INVIO DESC;


 WITH M_CON AS (SELECT REF_ID_COM, ROW_NUMBER() OVER(ORDER BY REF_ID_COM DESC) AS RN 
  FROM[FAXPEC].[FAXPEC].[MAIL_CONTENT] MC WHERE MAIL_SENDER = 'n.ruberto@deltamanagement.it' 
  AND FOLDERTIPO='O' AND FOLDERID=2) SELECT convert(varchar, MC.ID_MAIL) AS 'MAIL_ID', MC.MAIL_SENDER AS 'MAIL_FROM',  
  MC.MAIL_SUBJECT, SUBSTRING(MC.MAIL_TEXT, 1, 150) as 'MAIL_TEXT', FOLDERID,
    FOLDERTIPO, R.MAIL_TO, '' as 'MAIL_CC', '' as 'MAIL_CCN', FL.STATO_COMUNICAZIONE_NEW  
	 AS 'STATUS_MAIL', FL1.DATA_OPERAZIONE  AS 'DATA_INVIO', (SELECT MAX(DATA_OPERAZIONE)  
	    FROM FAXPEC.COMUNICAZIONI_FLUSSO    WHERE REF_ID_COM = MC.REF_ID_COM   AND STATO_COMUNICAZIONE_NEW IN ('28', '29'))
		 AS 'DATA_RICEZIONE', MC.FLG_ANNULLAMENTO AS 'STATUS_SERVER', NULL as 'FLG_RATING', 
		   IIF(((SELECT COUNT(*) FROM[FAXPEC].[FAXPEC].[COMUNICAZIONI_ALLEGATI] al    
		     WHERE  al.REF_ID_COM = MC.REF_ID_COM) = 0), '0', '1') AS 'FLG_ATTACHMENTS',  
			   (SELECT UTE_OPE FROM[FAXPEC].[FAXPEC].[COMUNICAZIONI_FLUSSO]    
			     fU WHERE fu.REF_ID_COM = MC.REF_ID_COM AND   STATO_COMUNICAZIONE_NEW = '20') AS 'UTENTE' ,
				 0 AS MSG_LENGTH  FROM    [FAXPEC].[FAXPEC].[MAIL_CONTENT]  MC LEFT OUTER
				  JOIN[FAXPEC].[FAXPEC].[COMUNICAZIONI_FLUSSO]    FL 
				  ON MC.REF_ID_FLUSSO_ATTUALE=FL.ID_FLUSSO LEFT OUTER JOIN[FAXPEC].[FAXPEC].[COMUNICAZIONI_FLUSSO]  
				    FL1 ON MC.REF_ID_FLUSSO_INSERIMENTO=FL1.ID_FLUSSO LEFT OUTER JOIN 
					 (SELECT REF_ID_MAIL, MAIL_DESTINATARIO AS 'MAIL_TO'  FROM[FAXPEC].MAIL_REFS_NEW  )
					  R ON MC.ID_MAIL = R.REF_ID_MAIL WHERE MAIL_SENDER = 'n.ruberto@deltamanagement.it' 
					  	 AND FOLDERTIPO = 'O' AND FOLDERID = 2 AND MC.REF_ID_COM  IN (SELECT REF_ID_COM FROM  
						  M_CON WHERE RN BETWEEN 1 AND 25) 
 ORDER BY DATA_INVIO DESC;