CREATE TABLE [FAXPEC].[COMUNICAZIONI_FLUSSO] (
    [REF_ID_COM]              NUMERIC (10)  NOT NULL,
    [STATO_COMUNICAZIONE_OLD] VARCHAR (2)   NULL,
    [STATO_COMUNICAZIONE_NEW] VARCHAR (2)   NOT NULL,
    [DATA_OPERAZIONE]         DATETIME2 (6) DEFAULT (sysdatetime()) NOT NULL,
    [UTE_OPE]                 VARCHAR (50)  NOT NULL,
    [CANALE]                  VARCHAR (20)  NOT NULL,
    [ID_FLUSSO]               FLOAT (53)    NOT NULL,
    CONSTRAINT [COMUNICAZIONI_FLUSSO_PK] PRIMARY KEY CLUSTERED ([ID_FLUSSO] ASC),
    CONSTRAINT [COMUNICAZIONI_FLUSSO_CHK1] CHECK ([STATO_COMUNICAZIONE_OLD]='99' OR [STATO_COMUNICAZIONE_OLD]='31' OR [STATO_COMUNICAZIONE_OLD]='30' OR [STATO_COMUNICAZIONE_OLD]='25' OR [STATO_COMUNICAZIONE_OLD]='24' OR [STATO_COMUNICAZIONE_OLD]='23' OR [STATO_COMUNICAZIONE_OLD]='22' OR [STATO_COMUNICAZIONE_OLD]='21' OR [STATO_COMUNICAZIONE_OLD]='20' OR [STATO_COMUNICAZIONE_OLD]='6' OR [STATO_COMUNICAZIONE_OLD]='5' OR [STATO_COMUNICAZIONE_OLD]='4' OR [STATO_COMUNICAZIONE_OLD]='3' OR [STATO_COMUNICAZIONE_OLD]='2' OR [STATO_COMUNICAZIONE_OLD]='1' OR [STATO_COMUNICAZIONE_OLD]='0'),
    CONSTRAINT [COMUNICAZIONI_FLUSSO_CHK2] CHECK ([STATO_COMUNICAZIONE_NEW]='99' OR [STATO_COMUNICAZIONE_NEW]='31' OR [STATO_COMUNICAZIONE_NEW]='30' OR [STATO_COMUNICAZIONE_NEW]='25' OR [STATO_COMUNICAZIONE_NEW]='24' OR [STATO_COMUNICAZIONE_NEW]='23' OR [STATO_COMUNICAZIONE_NEW]='22' OR [STATO_COMUNICAZIONE_NEW]='21' OR [STATO_COMUNICAZIONE_NEW]='20' OR [STATO_COMUNICAZIONE_NEW]='6' OR [STATO_COMUNICAZIONE_NEW]='5' OR [STATO_COMUNICAZIONE_NEW]='4' OR [STATO_COMUNICAZIONE_NEW]='3' OR [STATO_COMUNICAZIONE_NEW]='2' OR [STATO_COMUNICAZIONE_NEW]='1' OR [STATO_COMUNICAZIONE_NEW]='0'),
    CONSTRAINT [COMUNICAZIONI_FLUSSO_COMU_FK1] FOREIGN KEY ([REF_ID_COM]) REFERENCES [FAXPEC].[COMUNICAZIONI] ([ID_COM]) ON DELETE CASCADE
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [COMUNICAZIONI_FLUSSO_IDX3]
    ON [FAXPEC].[COMUNICAZIONI_FLUSSO]([REF_ID_COM] DESC, [DATA_OPERAZIONE] DESC);


GO
CREATE NONCLUSTERED INDEX [COMUNICAZIONI_FLUSSO_INDEX1]
    ON [FAXPEC].[COMUNICAZIONI_FLUSSO]([REF_ID_COM] ASC);


GO
CREATE NONCLUSTERED INDEX [COMUNICAZIONI_FLUSSO_INDEX2]
    ON [FAXPEC].[COMUNICAZIONI_FLUSSO]([DATA_OPERAZIONE] ASC);


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$COMUNICAZIONI_FLUSSO]
   ON [FAXPEC].[COMUNICAZIONI_FLUSSO]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE             
               @new$REF_ID_COM numeric(10, 0), 
               @new$STATO_COMUNICAZIONE_OLD varchar(2), 
               @new$STATO_COMUNICAZIONE_NEW varchar(2), 
               @new$DATA_OPERAZIONE datetime2(6), 
               @new$UTE_OPE varchar(50), 
               @new$CANALE varchar(20), 
               /*
               *   SSMA warning messages:
               *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
               */

               @new$ID_FLUSSO float(53)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT
                   
                     REF_ID_COM, 
                     STATO_COMUNICAZIONE_OLD, 
                     STATO_COMUNICAZIONE_NEW, 
                     DATA_OPERAZIONE, 
                     UTE_OPE, 
                     CANALE, 
                     ID_FLUSSO
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                  
                  @new$REF_ID_COM, 
                  @new$STATO_COMUNICAZIONE_OLD, 
                  @new$STATO_COMUNICAZIONE_NEW, 
                  @new$DATA_OPERAZIONE, 
                  @new$UTE_OPE, 
                  @new$CANALE, 
                  @new$ID_FLUSSO

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN

                        COLUMN_SEQUENCES:

                        BEGIN
                           IF @triggerType = 'I' 
                              SELECT @new$ID_FLUSSO = NEXT VALUE FOR FAXPEC.COMUNICAZIONI_FLUSSO_SEQ
                        END

                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.COMUNICAZIONI_FLUSSO(                    
                     REF_ID_COM, 
                     STATO_COMUNICAZIONE_OLD, 
                     STATO_COMUNICAZIONE_NEW, 
                     DATA_OPERAZIONE, 
                     UTE_OPE, 
                     CANALE, 
                     ID_FLUSSO)
                     VALUES (                     
                        @new$REF_ID_COM, 
                        @new$STATO_COMUNICAZIONE_OLD, 
                        @new$STATO_COMUNICAZIONE_NEW, 
                        @new$DATA_OPERAZIONE, 
                        @new$UTE_OPE, 
                        @new$CANALE, 
                        @new$ID_FLUSSO)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                        
                        @new$REF_ID_COM, 
                        @new$STATO_COMUNICAZIONE_OLD, 
                        @new$STATO_COMUNICAZIONE_NEW, 
                        @new$DATA_OPERAZIONE, 
                        @new$UTE_OPE, 
                        @new$CANALE, 
                        @new$ID_FLUSSO

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO

CREATE TRIGGER [FAXPEC].[TRG_COM_FLUSSO_TO_MAIL_CONTENT$AfterInsert]
   ON [FAXPEC].[COMUNICAZIONI_FLUSSO]
    AFTER INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            /* column variables declaration*/
            DECLARE              
               @new$REF_ID_COM numeric(10, 0), 
               @new$STATO_COMUNICAZIONE_NEW varchar(2), 
               /*
               *   SSMA warning messages:
               *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
               */

               @new$ID_FLUSSO float(53)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT REF_ID_COM, STATO_COMUNICAZIONE_NEW, ID_FLUSSO
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO @new$REF_ID_COM, @new$STATO_COMUNICAZIONE_NEW, @new$ID_FLUSSO

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* trigger implementation: begin*/
                  BEGIN

                     UPDATE FAXPEC.MAIL_CONTENT
                        SET 
                           REF_ID_FLUSSO_ATTUALE = @new$ID_FLUSSO
                     WHERE MAIL_CONTENT.REF_ID_COM = @new$REF_ID_COM

                     IF @new$STATO_COMUNICAZIONE_NEW IN ( 20, 23 )
                        UPDATE FAXPEC.MAIL_CONTENT
                           SET 
                              REF_ID_FLUSSO_INSERIMENTO = @new$ID_FLUSSO
                        WHERE MAIL_CONTENT.REF_ID_COM = @new$REF_ID_COM
                     ELSE 
                        DECLARE
                           @db_null_statement int

                  END
                  /* trigger implementation: end*/

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO  @new$REF_ID_COM, @new$STATO_COMUNICAZIONE_NEW, @new$ID_FLUSSO

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.COMUNICAZIONI_FLUSSO_IDX3', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'INDEX', @level2name = N'COMUNICAZIONI_FLUSSO_IDX3';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.COMUNICAZIONI_FLUSSO_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'INDEX', @level2name = N'COMUNICAZIONI_FLUSSO_INDEX1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.COMUNICAZIONI_FLUSSO_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'INDEX', @level2name = N'COMUNICAZIONI_FLUSSO_INDEX2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.REF_ID_COM', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'COLUMN', @level2name = N'REF_ID_COM';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.STATO_COMUNICAZIONE_OLD', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'COLUMN', @level2name = N'STATO_COMUNICAZIONE_OLD';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.STATO_COMUNICAZIONE_NEW', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'COLUMN', @level2name = N'STATO_COMUNICAZIONE_NEW';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.DATA_OPERAZIONE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'COLUMN', @level2name = N'DATA_OPERAZIONE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.UTE_OPE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'COLUMN', @level2name = N'UTE_OPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.CANALE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'COLUMN', @level2name = N'CANALE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.ID_FLUSSO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'COLUMN', @level2name = N'ID_FLUSSO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.COMUNICAZIONI_FLUSSO_CHK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'CONSTRAINT', @level2name = N'COMUNICAZIONI_FLUSSO_CHK1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.COMUNICAZIONI_FLUSSO_CHK2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'CONSTRAINT', @level2name = N'COMUNICAZIONI_FLUSSO_CHK2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.COMUNICAZIONI_FLUSSO_COMU_FK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'CONSTRAINT', @level2name = N'COMUNICAZIONI_FLUSSO_COMU_FK1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_FLUSSO.COMUNICAZIONI_FLUSSO_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_FLUSSO', @level2type = N'CONSTRAINT', @level2name = N'COMUNICAZIONI_FLUSSO_PK';

