CREATE TABLE [FAXPEC].[COMUNICAZIONI_ENTITA_USED] (
    [REF_ID_COMUNICAZIONE] NUMERIC (10) NOT NULL,
    [REF_ID_ENTITA]        NUMERIC (10) NULL,
    [REF_ID_ENT_USED]      NUMERIC (10) NOT NULL,
    CONSTRAINT [COMUNICAZIONI_ENTITA_USED_PK] PRIMARY KEY CLUSTERED ([REF_ID_COMUNICAZIONE] ASC, [REF_ID_ENT_USED] ASC),
    CONSTRAINT [COMUNICAZIONI_ENTITA_USED_FK1] FOREIGN KEY ([REF_ID_COMUNICAZIONE]) REFERENCES [FAXPEC].[COMUNICAZIONI] ([ID_COM]) ON DELETE CASCADE,
    CONSTRAINT [COMUNICAZIONI_ENTITA_USED_FK2] FOREIGN KEY ([REF_ID_ENT_USED]) REFERENCES [FAXPEC].[COMUNICAZIONI_DESTINATARI] ([ID_COM_DEST]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [COMUNICAZIONI_ENT_USED_INDEX1]
    ON [FAXPEC].[COMUNICAZIONI_ENTITA_USED]([REF_ID_ENTITA] ASC);


GO
CREATE NONCLUSTERED INDEX [COMUNICAZIONI_ENT_USED_INDEX2]
    ON [FAXPEC].[COMUNICAZIONI_ENTITA_USED]([REF_ID_ENT_USED] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.COMUNICAZIONI_ENT_USED_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'INDEX', @level2name = N'COMUNICAZIONI_ENT_USED_INDEX1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.COMUNICAZIONI_ENT_USED_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'INDEX', @level2name = N'COMUNICAZIONI_ENT_USED_INDEX2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.REF_ID_COMUNICAZIONE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'COLUMN', @level2name = N'REF_ID_COMUNICAZIONE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.REF_ID_ENTITA', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'COLUMN', @level2name = N'REF_ID_ENTITA';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.REF_ID_ENT_USED', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'COLUMN', @level2name = N'REF_ID_ENT_USED';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.COMUNICAZIONI_ENTITA_USED_FK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'CONSTRAINT', @level2name = N'COMUNICAZIONI_ENTITA_USED_FK1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.COMUNICAZIONI_ENTITA_USED_FK2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'CONSTRAINT', @level2name = N'COMUNICAZIONI_ENTITA_USED_FK2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_ENTITA_USED.COMUNICAZIONI_ENTITA_USED_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_ENTITA_USED', @level2type = N'CONSTRAINT', @level2name = N'COMUNICAZIONI_ENTITA_USED_PK';

