CREATE TABLE [FAXPEC].[COMUNICAZIONI_DESTINATARI] (
    [ID_COM_DEST]     NUMERIC (10)    NOT NULL,
    [MAIL]            NVARCHAR (256)  NULL,
    [FAX]             VARCHAR (50)    NULL,
    [TELEFONO]        VARCHAR (50)    NULL,
    [CONTACT_REF]     NVARCHAR (200)  NULL,
    [REFERRAL_TYPE]   VARCHAR (20)    NULL,
    [COGNOME]         NVARCHAR (200)  NULL,
    [NOME]            NVARCHAR (100)  NULL,
    [COD_FIS]         VARCHAR (16)    NULL,
    [P_IVA]           VARCHAR (11)    NULL,
    [RAGIONE_SOCIALE] NVARCHAR (100)  NULL,
    [UFFICIO]         NVARCHAR (1000) NULL,
    [NOTE]            NVARCHAR (200)  NULL,
    [INDIRIZZO]       NVARCHAR (200)  NULL,
    [CIVICO]          VARCHAR (20)    NULL,
    [CAP]             VARCHAR (5)     NULL,
    [COMUNE]          NVARCHAR (100)  NULL,
    [SIGLA_PROV]      VARCHAR (2)     NULL,
    [COD_ISO_STATO]   NVARCHAR (5)    NULL,
    [ID_REFERRAL]     NUMERIC (10)    NULL,
    CONSTRAINT [COM_DESTINATARI_PK] PRIMARY KEY CLUSTERED ([ID_COM_DEST] ASC),
    CONSTRAINT [COMUNICAZIONI_DESTINATARI_FK1] FOREIGN KEY ([ID_REFERRAL]) REFERENCES [FAXPEC].[RUBR_ENTITA] ([ID_REFERRAL])
);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX1]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([MAIL] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX2]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([FAX] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX3]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([TELEFONO] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX4]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([COGNOME] ASC, [NOME] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX5]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([CONTACT_REF] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX6]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([COD_FIS] ASC, [P_IVA] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX7]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([COD_ISO_STATO] ASC, [SIGLA_PROV] ASC, [COMUNE] ASC, [CAP] ASC, [INDIRIZZO] ASC, [CIVICO] ASC);


GO
CREATE NONCLUSTERED INDEX [COM_DEST_INDEX8]
    ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]([ID_REFERRAL] ASC);


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$COMUNICAZIONI_DESTINATARI]
   ON [FAXPEC].[COMUNICAZIONI_DESTINATARI]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE             
               @new$ID_COM_DEST numeric(10, 0), 
               @new$MAIL nvarchar(256), 
               @new$FAX varchar(50), 
               @new$TELEFONO varchar(50), 
               @new$CONTACT_REF nvarchar(200), 
               @new$REFERRAL_TYPE varchar(20), 
               @new$COGNOME nvarchar(200), 
               @new$NOME nvarchar(100), 
               @new$COD_FIS varchar(16), 
               @new$P_IVA varchar(11), 
               @new$RAGIONE_SOCIALE nvarchar(100), 
               @new$UFFICIO nvarchar(1000), 
               @new$NOTE nvarchar(200), 
               @new$INDIRIZZO nvarchar(200), 
               @new$CIVICO varchar(20), 
               @new$CAP varchar(5), 
               @new$COMUNE nvarchar(100), 
               @new$SIGLA_PROV varchar(2), 
               @new$COD_ISO_STATO nvarchar(5), 
               @new$ID_REFERRAL numeric(10, 0)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT                     
                     ID_COM_DEST, 
                     MAIL, 
                     FAX, 
                     TELEFONO, 
                     CONTACT_REF, 
                     REFERRAL_TYPE, 
                     COGNOME, 
                     NOME, 
                     COD_FIS, 
                     P_IVA, 
                     RAGIONE_SOCIALE, 
                     UFFICIO, 
                     NOTE, 
                     INDIRIZZO, 
                     CIVICO, 
                     CAP, 
                     COMUNE, 
                     SIGLA_PROV, 
                     COD_ISO_STATO, 
                     ID_REFERRAL
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                 
                  @new$ID_COM_DEST, 
                  @new$MAIL, 
                  @new$FAX, 
                  @new$TELEFONO, 
                  @new$CONTACT_REF, 
                  @new$REFERRAL_TYPE, 
                  @new$COGNOME, 
                  @new$NOME, 
                  @new$COD_FIS, 
                  @new$P_IVA, 
                  @new$RAGIONE_SOCIALE, 
                  @new$UFFICIO, 
                  @new$NOTE, 
                  @new$INDIRIZZO, 
                  @new$CIVICO, 
                  @new$CAP, 
                  @new$COMUNE, 
                  @new$SIGLA_PROV, 
                  @new$COD_ISO_STATO, 
                  @new$ID_REFERRAL

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN
                        IF @triggerType = 'I'
                           BEGIN                             
                                 SELECT @new$ID_COM_DEST = NEXT VALUE FOR FAXPEC.RUBR_ENTITA_USED_SEQ
                           END
                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.COMUNICAZIONI_DESTINATARI(                   
                     ID_COM_DEST, 
                     MAIL, 
                     FAX, 
                     TELEFONO, 
                     CONTACT_REF, 
                     REFERRAL_TYPE, 
                     COGNOME, 
                     NOME, 
                     COD_FIS, 
                     P_IVA, 
                     RAGIONE_SOCIALE, 
                     UFFICIO, 
                     NOTE, 
                     INDIRIZZO, 
                     CIVICO, 
                     CAP, 
                     COMUNE, 
                     SIGLA_PROV, 
                     COD_ISO_STATO, 
                     ID_REFERRAL)
                     VALUES (                      
                        @new$ID_COM_DEST, 
                        @new$MAIL, 
                        @new$FAX, 
                        @new$TELEFONO, 
                        @new$CONTACT_REF, 
                        @new$REFERRAL_TYPE, 
                        @new$COGNOME, 
                        @new$NOME, 
                        @new$COD_FIS, 
                        @new$P_IVA, 
                        @new$RAGIONE_SOCIALE, 
                        @new$UFFICIO, 
                        @new$NOTE, 
                        @new$INDIRIZZO, 
                        @new$CIVICO, 
                        @new$CAP, 
                        @new$COMUNE, 
                        @new$SIGLA_PROV, 
                        @new$COD_ISO_STATO, 
                        @new$ID_REFERRAL)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                       
                        @new$ID_COM_DEST, 
                        @new$MAIL, 
                        @new$FAX, 
                        @new$TELEFONO, 
                        @new$CONTACT_REF, 
                        @new$REFERRAL_TYPE, 
                        @new$COGNOME, 
                        @new$NOME, 
                        @new$COD_FIS, 
                        @new$P_IVA, 
                        @new$RAGIONE_SOCIALE, 
                        @new$UFFICIO, 
                        @new$NOTE, 
                        @new$INDIRIZZO, 
                        @new$CIVICO, 
                        @new$CAP, 
                        @new$COMUNE, 
                        @new$SIGLA_PROV, 
                        @new$COD_ISO_STATO, 
                        @new$ID_REFERRAL

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX3', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX3';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX4', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX4';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX5', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX5';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX6', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX6';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX7', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX7';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DEST_INDEX8', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'INDEX', @level2name = N'COM_DEST_INDEX8';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COM_DESTINATARI_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'CONSTRAINT', @level2name = N'COM_DESTINATARI_PK';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.ID_COM_DEST', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'ID_COM_DEST';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.MAIL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'MAIL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.FAX', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'FAX';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.TELEFONO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'TELEFONO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.CONTACT_REF', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'CONTACT_REF';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.REFERRAL_TYPE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'REFERRAL_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COGNOME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'COGNOME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.NOME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'NOME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COD_FIS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'COD_FIS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.P_IVA', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'P_IVA';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.RAGIONE_SOCIALE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'RAGIONE_SOCIALE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.UFFICIO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'UFFICIO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.NOTE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'NOTE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.INDIRIZZO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'INDIRIZZO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.CIVICO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'CIVICO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.CAP', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'CAP';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COMUNE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'COMUNE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.SIGLA_PROV', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'SIGLA_PROV';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.COD_ISO_STATO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'COD_ISO_STATO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_DESTINATARI.ID_REFERRAL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'COMUNICAZIONI_DESTINATARI', @level2type = N'COLUMN', @level2name = N'ID_REFERRAL';

