CREATE TABLE [FAXPEC].[LOG_ERRORS] (
    [ID]                NUMERIC (10)  NOT NULL,
    [LOG_UID]           VARCHAR (40)  NULL,
    [APP_CODE]          VARCHAR (20)  NULL,
    [LOG_CODE]          VARCHAR (20)  NULL,
    [LOG_DATE]          DATETIME2 (6) NULL,
    [DETAILS]           VARCHAR (MAX) NULL,
    [USER_ID]           VARCHAR (255) NULL,
    [USER_IP]           VARCHAR (20)  NULL,
    [OBJ_ID]            VARCHAR (30)  NULL,
    [OBJ_GRP_ID]        VARCHAR (20)  NULL,
    [OBJ_APP_ID]        VARCHAR (20)  NULL,
    [OBJ_PAR_CODE]      VARCHAR (20)  NULL,
    [PASS_OBJ_ID]       VARCHAR (20)  NULL,
    [PASS_OBJ_GRP_ID]   VARCHAR (20)  NULL,
    [PASS_OBJ_APP_ID]   VARCHAR (20)  NULL,
    [PASS_OBJ_PAR_CODE] VARCHAR (20)  NULL,
    [LOG_LEVEL]         VARCHAR (10)  NULL,
    CONSTRAINT [LOG_ERRORS_PK] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$LOG_ERRORS]
   ON [FAXPEC].[LOG_ERRORS]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE             
               @new$ID numeric(10, 0), 
               @new$LOG_UID varchar(40), 
               @new$APP_CODE varchar(20), 
               @new$LOG_CODE varchar(20), 
               @new$LOG_DATE datetime2(6), 
               @new$DETAILS varchar(max), 
               @new$USER_ID varchar(255), 
               @new$USER_IP varchar(20), 
               @new$OBJ_ID varchar(30), 
               @new$OBJ_GRP_ID varchar(20), 
               @new$OBJ_APP_ID varchar(20), 
               @new$OBJ_PAR_CODE varchar(20), 
               @new$PASS_OBJ_ID varchar(20), 
               @new$PASS_OBJ_GRP_ID varchar(20), 
               @new$PASS_OBJ_APP_ID varchar(20), 
               @new$PASS_OBJ_PAR_CODE varchar(20), 
               @new$LOG_LEVEL varchar(10)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT                   
                     ID, 
                     LOG_UID, 
                     APP_CODE, 
                     LOG_CODE, 
                     LOG_DATE, 
                     DETAILS, 
                     USER_ID, 
                     USER_IP, 
                     OBJ_ID, 
                     OBJ_GRP_ID, 
                     OBJ_APP_ID, 
                     OBJ_PAR_CODE, 
                     PASS_OBJ_ID, 
                     PASS_OBJ_GRP_ID, 
                     PASS_OBJ_APP_ID, 
                     PASS_OBJ_PAR_CODE, 
                     LOG_LEVEL
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                
                  @new$ID, 
                  @new$LOG_UID, 
                  @new$APP_CODE, 
                  @new$LOG_CODE, 
                  @new$LOG_DATE, 
                  @new$DETAILS, 
                  @new$USER_ID, 
                  @new$USER_IP, 
                  @new$OBJ_ID, 
                  @new$OBJ_GRP_ID, 
                  @new$OBJ_APP_ID, 
                  @new$OBJ_PAR_CODE, 
                  @new$PASS_OBJ_ID, 
                  @new$PASS_OBJ_GRP_ID, 
                  @new$PASS_OBJ_APP_ID, 
                  @new$PASS_OBJ_PAR_CODE, 
                  @new$LOG_LEVEL

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN
                        IF @triggerType = 'I'
                           BEGIN
                              IF @new$ID IS NULL
                                 SELECT @new$ID = NEXT VALUE FOR FAXPEC.LOG_ACTIONS_SEQ
                           END
                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.LOG_ERRORS(                    
                     ID, 
                     LOG_UID, 
                     APP_CODE, 
                     LOG_CODE, 
                     LOG_DATE, 
                     DETAILS, 
                     USER_ID, 
                     USER_IP, 
                     OBJ_ID, 
                     OBJ_GRP_ID, 
                     OBJ_APP_ID, 
                     OBJ_PAR_CODE, 
                     PASS_OBJ_ID, 
                     PASS_OBJ_GRP_ID, 
                     PASS_OBJ_APP_ID, 
                     PASS_OBJ_PAR_CODE, 
                     LOG_LEVEL)
                     VALUES (                      
                        @new$ID, 
                        @new$LOG_UID, 
                        @new$APP_CODE, 
                        @new$LOG_CODE, 
                        @new$LOG_DATE, 
                        @new$DETAILS, 
                        @new$USER_ID, 
                        @new$USER_IP, 
                        @new$OBJ_ID, 
                        @new$OBJ_GRP_ID, 
                        @new$OBJ_APP_ID, 
                        @new$OBJ_PAR_CODE, 
                        @new$PASS_OBJ_ID, 
                        @new$PASS_OBJ_GRP_ID, 
                        @new$PASS_OBJ_APP_ID, 
                        @new$PASS_OBJ_PAR_CODE, 
                        @new$LOG_LEVEL)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                       
                        @new$ID, 
                        @new$LOG_UID, 
                        @new$APP_CODE, 
                        @new$LOG_CODE, 
                        @new$LOG_DATE, 
                        @new$DETAILS, 
                        @new$USER_ID, 
                        @new$USER_IP, 
                        @new$OBJ_ID, 
                        @new$OBJ_GRP_ID, 
                        @new$OBJ_APP_ID, 
                        @new$OBJ_PAR_CODE, 
                        @new$PASS_OBJ_ID, 
                        @new$PASS_OBJ_GRP_ID, 
                        @new$PASS_OBJ_APP_ID, 
                        @new$PASS_OBJ_PAR_CODE, 
                        @new$LOG_LEVEL

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.LOG_UID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'LOG_UID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.APP_CODE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'APP_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.LOG_CODE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'LOG_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.LOG_DATE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'LOG_DATE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.DETAILS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'DETAILS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.USER_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'USER_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.USER_IP', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'USER_IP';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.OBJ_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'OBJ_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.OBJ_GRP_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'OBJ_GRP_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.OBJ_APP_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'OBJ_APP_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.OBJ_PAR_CODE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'OBJ_PAR_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.PASS_OBJ_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'PASS_OBJ_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.PASS_OBJ_GRP_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'PASS_OBJ_GRP_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.PASS_OBJ_APP_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'PASS_OBJ_APP_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.PASS_OBJ_PAR_CODE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'PASS_OBJ_PAR_CODE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.LOG_LEVEL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'COLUMN', @level2name = N'LOG_LEVEL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.LOG_ERRORS.LOG_ERRORS_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'LOG_ERRORS', @level2type = N'CONSTRAINT', @level2name = N'LOG_ERRORS_PK';

