CREATE TABLE [FAXPEC].[MAIL_INBOX_FLUSSO] (
    [REF_ID_MAIL]     NUMERIC (10)  NOT NULL,
    [STATUS_MAIL_OLD] VARCHAR (2)   NULL,
    [STATUS_MAIL_NEW] VARCHAR (2)   NOT NULL,
    [DATA_OPERAZIONE] DATETIME2 (0) DEFAULT (sysdatetime()) NOT NULL,
    [UTE_OPE]         VARCHAR (50)  NOT NULL,
    [ID_FLUSSO]       BIGINT        NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_FLUSSO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MAIL_INBOX_FLUSSO_INDEX1]
    ON [FAXPEC].[MAIL_INBOX_FLUSSO]([REF_ID_MAIL] ASC);


GO
CREATE NONCLUSTERED INDEX [MAIL_INBOX_FLUSSO_INDEX2]
    ON [FAXPEC].[MAIL_INBOX_FLUSSO]([REF_ID_MAIL] ASC, [STATUS_MAIL_OLD] ASC, [STATUS_MAIL_NEW] ASC);


GO
CREATE NONCLUSTERED INDEX [MAIL_INBOX_FLUSSO_INDEX3]
    ON [FAXPEC].[MAIL_INBOX_FLUSSO]([UTE_OPE] ASC);


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$MAIL_INBOX_FLUSSO]
   ON [FAXPEC].[MAIL_INBOX_FLUSSO]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            /* column variables declaration*/
            DECLARE     
			     @triggerType char(1)

            SELECT @triggerType = 'I'
			       
				   DECLARE
               @new$REF_ID_MAIL numeric(10, 0), 
               @new$STATUS_MAIL_OLD varchar(2), 
               @new$STATUS_MAIL_NEW varchar(2), 
               @new$DATA_OPERAZIONE datetime2(0), 
               @new$UTE_OPE varchar(50),
			   @new$ID int

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT        
				     ID_FLUSSO,             
                     REF_ID_MAIL, 
                     STATUS_MAIL_OLD, 
                     STATUS_MAIL_NEW, 
                     DATA_OPERAZIONE, 
                     UTE_OPE
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO     
				  @new$ID,             
                  @new$REF_ID_MAIL, 
                  @new$STATUS_MAIL_OLD, 
                  @new$STATUS_MAIL_NEW, 
                  @new$DATA_OPERAZIONE, 
                  @new$UTE_OPE

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     IF (@new$STATUS_MAIL_OLD = @new$STATUS_MAIL_NEW)
                        BEGIN
                           RAISERROR(59999, 16, 1, N'ORA-06502%')
                        END
                  END
                  /* row-level triggers implementation: end*/
				    BEGIN
                     BEGIN
                        IF @triggerType = 'I'
                           BEGIN                           
                                 SELECT @new$ID = NEXT VALUE FOR FAXPEC.MAIL_INBOX_FLUSSO_SEQ
                           END
                     END
                  END

                  /* DML-operation emulation*/
                  INSERT FAXPEC.MAIL_INBOX_FLUSSO(   
				     ID_FLUSSO,                 
                     REF_ID_MAIL, 
                     STATUS_MAIL_OLD, 
                     STATUS_MAIL_NEW, 
                     DATA_OPERAZIONE, 
                     UTE_OPE)
                     VALUES (    
					    @new$ID,                  
                        @new$REF_ID_MAIL, 
                        @new$STATUS_MAIL_OLD, 
                        @new$STATUS_MAIL_NEW, 
                        @new$DATA_OPERAZIONE, 
                        @new$UTE_OPE)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO         
					    @new$ID,                
                        @new$REF_ID_MAIL, 
                        @new$STATUS_MAIL_OLD, 
                        @new$STATUS_MAIL_NEW, 
                        @new$DATA_OPERAZIONE, 
                        @new$UTE_OPE

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.MAIL_INBOX_FLUSSO_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'INDEX', @level2name = N'MAIL_INBOX_FLUSSO_INDEX1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.MAIL_INBOX_FLUSSO_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'INDEX', @level2name = N'MAIL_INBOX_FLUSSO_INDEX2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.MAIL_INBOX_FLUSSO_INDEX3', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'INDEX', @level2name = N'MAIL_INBOX_FLUSSO_INDEX3';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.REF_ID_MAIL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'COLUMN', @level2name = N'REF_ID_MAIL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.STATUS_MAIL_OLD', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'COLUMN', @level2name = N'STATUS_MAIL_OLD';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.STATUS_MAIL_NEW', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'COLUMN', @level2name = N'STATUS_MAIL_NEW';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.DATA_OPERAZIONE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'COLUMN', @level2name = N'DATA_OPERAZIONE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX_FLUSSO.UTE_OPE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX_FLUSSO', @level2type = N'COLUMN', @level2name = N'UTE_OPE';

