CREATE TABLE [FAXPEC].[MAIL_CONTENT] (
    [ID_MAIL]                   NUMERIC (10)    NOT NULL,
    [REF_ID_COM]                NUMERIC (10)    NOT NULL,
    [MAIL_SENDER]               NVARCHAR (200)  NOT NULL,
    [MAIL_SUBJECT]              NVARCHAR (1000) NULL,
    [MAIL_TEXT]                 VARCHAR (MAX)   NULL,
    [FLG_ANNULLAMENTO]          VARCHAR (1)     CONSTRAINT [DF__MAIL_CONT__FLG_A__33BFA6FF] DEFAULT ((0)) NULL,
    [FLG_CUSTOM_REFS]           VARCHAR (1)     CONSTRAINT [DF__MAIL_CONT__FLG_C__34B3CB38] DEFAULT ((0)) NOT NULL,
    [FOLLOWS]                   NUMERIC (10)    NULL,
    [FOLDERID]                  NUMERIC (18)    NOT NULL,
    [FOLDERTIPO]                VARCHAR (1)     NOT NULL,
    [REF_ID_SENDER]             NUMERIC (10)    NULL,
    [REF_ID_FLUSSO_ATTUALE]     FLOAT (53)      NULL,
    [REF_ID_FLUSSO_INSERIMENTO] FLOAT (53)      NULL,
    CONSTRAINT [MAIL_CONTENT_PK] PRIMARY KEY CLUSTERED ([ID_MAIL] ASC),
    CONSTRAINT [MAIL_CONTENT_CHK1] CHECK ([FLG_ANNULLAMENTO]='1' OR [FLG_ANNULLAMENTO]='0'),
    FOREIGN KEY ([FOLDERID]) REFERENCES [FAXPEC].[FOLDERS] ([ID]),
    CONSTRAINT [MAIL_CONTENT_COMUNICAZION_FK1] FOREIGN KEY ([REF_ID_COM]) REFERENCES [FAXPEC].[COMUNICAZIONI] ([ID_COM]) ON DELETE CASCADE,
    CONSTRAINT [MAIL_CONTENT_FLUSSI_FK1] FOREIGN KEY ([REF_ID_FLUSSO_ATTUALE]) REFERENCES [FAXPEC].[COMUNICAZIONI_FLUSSO] ([ID_FLUSSO]),
    CONSTRAINT [MAIL_CONTENT_FLUSSI_FK2] FOREIGN KEY ([REF_ID_FLUSSO_INSERIMENTO]) REFERENCES [FAXPEC].[COMUNICAZIONI_FLUSSO] ([ID_FLUSSO])
);


GO
CREATE NONCLUSTERED INDEX [MAIL_CONTENT_IDX_MAIL_SENDER]
    ON [FAXPEC].[MAIL_CONTENT]([MAIL_SENDER] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [MAIL_CONTENT_IDX_REF_ID_COM]
    ON [FAXPEC].[MAIL_CONTENT]([REF_ID_COM] ASC);


GO
CREATE NONCLUSTERED INDEX [MAIL_CONTENT_IDX_FOLLOWS]
    ON [FAXPEC].[MAIL_CONTENT]([FOLLOWS] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_MAILCONTENT_FOLDERS]
    ON [FAXPEC].[MAIL_CONTENT]([FOLDERID] ASC, [FOLDERTIPO] ASC);


GO
CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$MAIL_CONTENT]
   ON [FAXPEC].[MAIL_CONTENT]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE          
               @new$ID_MAIL numeric(10, 0), 
               @new$REF_ID_COM numeric(10, 0), 
               @new$MAIL_SENDER nvarchar(200), 
               @new$MAIL_SUBJECT nvarchar(1000), 
               @new$MAIL_TEXT varchar(max), 
               @new$FLG_ANNULLAMENTO varchar(1), 
               @new$FLG_CUSTOM_REFS varchar(1), 
               @new$FOLLOWS numeric(10, 0), 
               /*
               *   SSMA warning messages:
               *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
               */

               @new$FOLDERID float(53), 
               @new$FOLDERTIPO varchar(1), 
               @new$REF_ID_SENDER numeric(10, 0), 
               /*
               *   SSMA warning messages:
               *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
               */

               @new$REF_ID_FLUSSO_ATTUALE float(53), 
               /*
               *   SSMA warning messages:
               *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
               */

               @new$REF_ID_FLUSSO_INSERIMENTO float(53)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT                    
                     ID_MAIL, 
                     REF_ID_COM, 
                     MAIL_SENDER, 
                     MAIL_SUBJECT, 
                     MAIL_TEXT, 
                     FLG_ANNULLAMENTO, 
                     FLG_CUSTOM_REFS, 
                     FOLLOWS, 
                     FOLDERID, 
                     FOLDERTIPO, 
                     REF_ID_SENDER, 
                     REF_ID_FLUSSO_ATTUALE, 
                     REF_ID_FLUSSO_INSERIMENTO
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                  
                  @new$ID_MAIL, 
                  @new$REF_ID_COM, 
                  @new$MAIL_SENDER, 
                  @new$MAIL_SUBJECT, 
                  @new$MAIL_TEXT, 
                  @new$FLG_ANNULLAMENTO, 
                  @new$FLG_CUSTOM_REFS, 
                  @new$FOLLOWS, 
                  @new$FOLDERID, 
                  @new$FOLDERTIPO, 
                  @new$REF_ID_SENDER, 
                  @new$REF_ID_FLUSSO_ATTUALE, 
                  @new$REF_ID_FLUSSO_INSERIMENTO

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN

                        COLUMN_SEQUENCES:

                        BEGIN
                           IF @triggerType = 'I'
                              BEGIN                             
                                    SELECT @new$ID_MAIL = NEXT VALUE FOR FAXPEC.ID_MAIL_SEQ
                              END
                        END

                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.MAIL_CONTENT(                   
                     ID_MAIL, 
                     REF_ID_COM, 
                     MAIL_SENDER, 
                     MAIL_SUBJECT, 
                     MAIL_TEXT, 
                     FLG_ANNULLAMENTO, 
           FLG_CUSTOM_REFS, 
                     FOLLOWS, 
                     FOLDERID, 
                     FOLDERTIPO, 
                     REF_ID_SENDER, 
                     REF_ID_FLUSSO_ATTUALE, 
                     REF_ID_FLUSSO_INSERIMENTO)
                     VALUES (                      
                        @new$ID_MAIL, 
                        @new$REF_ID_COM, 
                        @new$MAIL_SENDER, 
                        @new$MAIL_SUBJECT, 
                        @new$MAIL_TEXT, 
                        @new$FLG_ANNULLAMENTO, 
                        @new$FLG_CUSTOM_REFS, 
                        @new$FOLLOWS, 
                        @new$FOLDERID, 
                        @new$FOLDERTIPO, 
                        @new$REF_ID_SENDER, 
                        @new$REF_ID_FLUSSO_ATTUALE, 
                        @new$REF_ID_FLUSSO_INSERIMENTO)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                        
                        @new$ID_MAIL, 
                        @new$REF_ID_COM, 
                        @new$MAIL_SENDER, 
                        @new$MAIL_SUBJECT, 
                        @new$MAIL_TEXT, 
                        @new$FLG_ANNULLAMENTO, 
                        @new$FLG_CUSTOM_REFS, 
                        @new$FOLLOWS, 
                        @new$FOLDERID, 
                        @new$FOLDERTIPO, 
                        @new$REF_ID_SENDER, 
                        @new$REF_ID_FLUSSO_ATTUALE, 
                        @new$REF_ID_FLUSSO_INSERIMENTO

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'INDEX', @level2name = N'MAIL_CONTENT_IDX_MAIL_SENDER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_CONTENT_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'INDEX', @level2name = N'MAIL_CONTENT_IDX_REF_ID_COM';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_CONTENT_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'INDEX', @level2name = N'MAIL_CONTENT_IDX_FOLLOWS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.ID_MAIL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'ID_MAIL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.REF_ID_COM', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'REF_ID_COM';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_SENDER', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'MAIL_SENDER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_SUBJECT', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'MAIL_SUBJECT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_TEXT', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'MAIL_TEXT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.FLG_ANNULLAMENTO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'FLG_ANNULLAMENTO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.FLG_CUSTOM_REFS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'FLG_CUSTOM_REFS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.FOLLOWS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'FOLLOWS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.FOLDERID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'FOLDERID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.FOLDERTIPO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'FOLDERTIPO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.REF_ID_SENDER', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'REF_ID_SENDER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.REF_ID_FLUSSO_ATTUALE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'REF_ID_FLUSSO_ATTUALE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.REF_ID_FLUSSO_INSERIMENTO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'COLUMN', @level2name = N'REF_ID_FLUSSO_INSERIMENTO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_CONTENT_CHK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'CONSTRAINT', @level2name = N'MAIL_CONTENT_CHK1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_CONTENT_COMUNICAZION_FK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'CONSTRAINT', @level2name = N'MAIL_CONTENT_COMUNICAZION_FK1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_CONTENT_FLUSSI_FK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'CONSTRAINT', @level2name = N'MAIL_CONTENT_FLUSSI_FK1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_CONTENT_FLUSSI_FK2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'CONSTRAINT', @level2name = N'MAIL_CONTENT_FLUSSI_FK2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_CONTENT.MAIL_CONTENT_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_CONTENT', @level2type = N'CONSTRAINT', @level2name = N'MAIL_CONTENT_PK';

