CREATE TABLE [FAXPEC].[MAIL_INBOX] (
    [MAIL_SERVER_ID]  VARCHAR (100)  NOT NULL,
    [MAIL_ACCOUNT]    VARCHAR (150)  NOT NULL,
    [MAIL_FROM]       VARCHAR (150)  NOT NULL,
    [MAIL_TO]         VARCHAR (1000) NULL,
    [MAIL_CC]         VARCHAR (1000) NULL,
    [MAIL_CCN]        VARCHAR (1000) NULL,
    [MAIL_SUBJECT]    VARCHAR (300)  NULL,
    [MAIL_TEXT]       VARCHAR (MAX)  NOT NULL,
    [DATA_INVIO]      DATETIME2 (0)  NOT NULL,
    [DATA_RICEZIONE]  DATETIME2 (0)  DEFAULT (sysdatetime()) NOT NULL,
    [STATUS_SERVER]   VARCHAR (1)    DEFAULT ((0)) NOT NULL,
    [STATUS_MAIL]     VARCHAR (2)    DEFAULT ((0)) NOT NULL,
    [FLG_INTEG_APPL]  VARCHAR (1)    DEFAULT ((0)) NOT NULL,
    [MAIL_FILE]       VARCHAR (MAX)  NULL,
    [FLG_RATING]      NUMERIC (1)    DEFAULT ((0)) NOT NULL,
    [REF_ID_COM]      NUMERIC (10)   NULL,
    [FLG_ATTACHMENTS] VARCHAR (1)    DEFAULT ((0)) NULL,
    [ID_MAIL]         NUMERIC (10)   NOT NULL,
    [MAIL_FOLDER]     VARCHAR (2)    DEFAULT ((1)) NULL,
    [FOLLOWS]         NUMERIC (10)   NULL,
    [MSG_LENGTH]      NUMERIC (20)   NULL,
    [FOLDERID]        NUMERIC (18)   NOT NULL,
    [FOLDERTIPO]      VARCHAR (1)    NOT NULL,
    [REF_ID_SENDER]   FLOAT (53)     NULL,
    CONSTRAINT [MAIL_INBOX_PK] PRIMARY KEY CLUSTERED ([ID_MAIL] ASC),
    CONSTRAINT [MAIL_INBOX_CHK1] CHECK ([FLG_RATING]=(4) OR [FLG_RATING]=(3) OR [FLG_RATING]=(2) OR [FLG_RATING]=(1) OR [FLG_RATING]=(0)),
    CONSTRAINT [MAIL_INBOX_CHK2] CHECK ([MAIL_FOLDER]='2' OR [MAIL_FOLDER]='1'),
    FOREIGN KEY ([FOLDERID]) REFERENCES [FAXPEC].[FOLDERS] ([ID]),
    CONSTRAINT [MAIL_INBOX_COMUNICAZIONI_FK1] FOREIGN KEY ([FOLDERID]) REFERENCES [FAXPEC].[FOLDERS] ([ID]),
    CONSTRAINT [MAIL_INBOX_UK_MAIL_SERVER_ID_MAIL_ACCOUNT] UNIQUE NONCLUSTERED ([MAIL_SERVER_ID] ASC, [MAIL_ACCOUNT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [MAIL_INBOX_IDX_FOLLOWS]
    ON [FAXPEC].[MAIL_INBOX]([FOLLOWS] ASC);


GO
CREATE NONCLUSTERED INDEX [MAIL_INBOX_MAIL_ACCOUNT]
    ON [FAXPEC].[MAIL_INBOX]([MAIL_ACCOUNT] ASC, [MAIL_FOLDER] ASC, [DATA_INVIO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_MAIL_INBOX_DATA_INVIO_MAIL_TO]
    ON [FAXPEC].[MAIL_INBOX]([DATA_INVIO] ASC, [MAIL_TO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_MAIL_INBOX_MAIL_ACCOUNT]
    ON [FAXPEC].[MAIL_INBOX]([MAIL_ACCOUNT] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MAIL_INBOX_FOLDER_ID]
    ON [FAXPEC].[MAIL_INBOX]([FOLDERID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MAIL_INBOX_FOLDERTIPO]
    ON [FAXPEC].[MAIL_INBOX]([FOLDERTIPO] ASC);


GO
CREATE NONCLUSTERED INDEX [IDX_MAILINBOX_FOLDERS]
    ON [FAXPEC].[MAIL_INBOX]([FOLDERID] ASC, [FOLDERTIPO] ASC);


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$MAIL_INBOX]
   ON [FAXPEC].[MAIL_INBOX]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE              
               @new$MAIL_SERVER_ID varchar(100), 
               @new$MAIL_ACCOUNT varchar(150), 
               @new$MAIL_FROM varchar(150), 
               @new$MAIL_TO varchar(1000), 
               @new$MAIL_CC varchar(1000), 
               @new$MAIL_CCN varchar(1000), 
               @new$MAIL_SUBJECT varchar(300), 
               @new$MAIL_TEXT varchar(150), 
               @new$DATA_INVIO datetime2(0), 
               @new$DATA_RICEZIONE datetime2(0), 
               @new$STATUS_SERVER varchar(1), 
               @new$STATUS_MAIL varchar(2), 
               @new$FLG_INTEG_APPL varchar(1), 
               @new$MAIL_FILE varchar(max), 
               @new$FLG_RATING numeric(1, 0), 
               @new$REF_ID_COM numeric(10, 0), 
               @new$FLG_ATTACHMENTS varchar(1), 
               @new$ID_MAIL numeric(10, 0), 
               @new$MAIL_FOLDER varchar(2), 
               @new$FOLLOWS numeric(10, 0), 
               @new$MSG_LENGTH numeric(20, 0), 
               /*
               *   SSMA warning messages:
               *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
               */

               @new$FOLDERID float(53), 
               @new$FOLDERTIPO varchar(1), 
               /*
               *   SSMA warning messages:
               *   O2SS0356: Conversion from NUMBER datatype can cause data loss.
               */

               @new$REF_ID_SENDER float(53)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT                    
                     MAIL_SERVER_ID, 
                     MAIL_ACCOUNT, 
                     MAIL_FROM, 
                     MAIL_TO, 
                     MAIL_CC, 
                     MAIL_CCN, 
                     MAIL_SUBJECT, 
                     MAIL_TEXT, 
                     DATA_INVIO, 
                     DATA_RICEZIONE, 
                     STATUS_SERVER, 
                     STATUS_MAIL, 
                     FLG_INTEG_APPL, 
                     MAIL_FILE, 
                     FLG_RATING, 
                     REF_ID_COM, 
                     FLG_ATTACHMENTS, 
                     ID_MAIL, 
                     MAIL_FOLDER, 
                     FOLLOWS, 
                     MSG_LENGTH, 
                     FOLDERID, 
                     FOLDERTIPO, 
                     REF_ID_SENDER
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                  
                  @new$MAIL_SERVER_ID, 
                  @new$MAIL_ACCOUNT, 
                  @new$MAIL_FROM, 
                  @new$MAIL_TO, 
                  @new$MAIL_CC, 
                  @new$MAIL_CCN, 
                  @new$MAIL_SUBJECT, 
                  @new$MAIL_TEXT, 
                  @new$DATA_INVIO, 
                  @new$DATA_RICEZIONE, 
                  @new$STATUS_SERVER, 
                  @new$STATUS_MAIL, 
                  @new$FLG_INTEG_APPL, 
                  @new$MAIL_FILE, 
                  @new$FLG_RATING, 
                  @new$REF_ID_COM, 
                  @new$FLG_ATTACHMENTS, 
                  @new$ID_MAIL, 
                  @new$MAIL_FOLDER, 
                  @new$FOLLOWS, 
                  @new$MSG_LENGTH, 
                  @new$FOLDERID, 
                  @new$FOLDERTIPO, 
                  @new$REF_ID_SENDER

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN
                        IF @triggerType = 'I'
                           BEGIN                           
                                 SELECT @new$ID_MAIL = NEXT VALUE FOR FAXPEC.ID_MAIL_SEQ
                           END
                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.MAIL_INBOX(                   
                     MAIL_SERVER_ID, 
                     MAIL_ACCOUNT, 
                     MAIL_FROM, 
                     MAIL_TO, 
                     MAIL_CC, 
                     MAIL_CCN, 
                     MAIL_SUBJECT, 
                     MAIL_TEXT, 
                     DATA_INVIO, 
                     DATA_RICEZIONE, 
                     STATUS_SERVER, 
                     STATUS_MAIL, 
                     FLG_INTEG_APPL, 
                     MAIL_FILE, 
                     FLG_RATING, 
                     REF_ID_COM, 
                     FLG_ATTACHMENTS, 
                     ID_MAIL, 
                     MAIL_FOLDER, 
                     FOLLOWS, 
                     MSG_LENGTH, 
                     FOLDERID, 
                     FOLDERTIPO, 
                     REF_ID_SENDER)
                     VALUES (                       
                        @new$MAIL_SERVER_ID, 
                        @new$MAIL_ACCOUNT, 
                        @new$MAIL_FROM, 
                        @new$MAIL_TO, 
                        @new$MAIL_CC, 
                        @new$MAIL_CCN, 
                        @new$MAIL_SUBJECT, 
                        @new$MAIL_TEXT, 
                        @new$DATA_INVIO, 
                        @new$DATA_RICEZIONE, 
                        @new$STATUS_SERVER, 
                        @new$STATUS_MAIL, 
                        @new$FLG_INTEG_APPL, 
                        @new$MAIL_FILE, 
                        @new$FLG_RATING, 
                        @new$REF_ID_COM, 
                        @new$FLG_ATTACHMENTS, 
                        @new$ID_MAIL, 
                        @new$MAIL_FOLDER, 
                        @new$FOLLOWS, 
                        @new$MSG_LENGTH, 
                        @new$FOLDERID, 
                        @new$FOLDERTIPO, 
                        @new$REF_ID_SENDER)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                        
                        @new$MAIL_SERVER_ID, 
                        @new$MAIL_ACCOUNT, 
                        @new$MAIL_FROM, 
                        @new$MAIL_TO, 
                        @new$MAIL_CC, 
                        @new$MAIL_CCN, 
                        @new$MAIL_SUBJECT, 
                        @new$MAIL_TEXT, 
                        @new$DATA_INVIO, 
                        @new$DATA_RICEZIONE, 
                        @new$STATUS_SERVER, 
                        @new$STATUS_MAIL, 
                        @new$FLG_INTEG_APPL, 
                        @new$MAIL_FILE, 
                        @new$FLG_RATING, 
                        @new$REF_ID_COM, 
                        @new$FLG_ATTACHMENTS, 
                        @new$ID_MAIL, 
                        @new$MAIL_FOLDER, 
                        @new$FOLLOWS, 
                        @new$MSG_LENGTH, 
                        @new$FOLDERID, 
                        @new$FOLDERTIPO, 
                        @new$REF_ID_SENDER

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_INBOX_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'INDEX', @level2name = N'MAIL_INBOX_IDX_FOLLOWS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_INBOX_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'INDEX', @level2name = N'MAIL_INBOX_MAIL_ACCOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.TABLE1_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'INDEX', @level2name = N'IDX_MAIL_INBOX_DATA_INVIO_MAIL_TO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.TABLE1_INDEX3', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'INDEX', @level2name = N'IDX_MAIL_INBOX_MAIL_ACCOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_SERVER_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_SERVER_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_ACCOUNT', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_ACCOUNT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_FROM', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_FROM';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_TO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_TO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_CC', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_CC';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_CCN', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_CCN';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_SUBJECT', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_SUBJECT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_TEXT', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_TEXT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.DATA_INVIO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'DATA_INVIO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.DATA_RICEZIONE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'DATA_RICEZIONE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.STATUS_SERVER', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'STATUS_SERVER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.STATUS_MAIL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'STATUS_MAIL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.FLG_INTEG_APPL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'FLG_INTEG_APPL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_FILE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_FILE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.FLG_RATING', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'FLG_RATING';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.REF_ID_COM', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'REF_ID_COM';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.FLG_ATTACHMENTS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'FLG_ATTACHMENTS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.ID_MAIL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'ID_MAIL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_FOLDER', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MAIL_FOLDER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.FOLLOWS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'FOLLOWS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MSG_LENGTH', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'MSG_LENGTH';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.FOLDERID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'FOLDERID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.FOLDERTIPO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'FOLDERTIPO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.REF_ID_SENDER', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'COLUMN', @level2name = N'REF_ID_SENDER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_INBOX_CHK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'CONSTRAINT', @level2name = N'MAIL_INBOX_CHK1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_INBOX_CHK2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'CONSTRAINT', @level2name = N'MAIL_INBOX_CHK2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_INBOX_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'CONSTRAINT', @level2name = N'MAIL_INBOX_PK';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_INBOX.MAIL_INBOX_UK1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_INBOX', @level2type = N'CONSTRAINT', @level2name = N'MAIL_INBOX_UK_MAIL_SERVER_ID_MAIL_ACCOUNT';

