CREATE TABLE [FAXPEC].[MAIL_USERS_BACKEND] (
    [ID_USER]        NUMERIC (10)  NOT NULL,
    [USER_NAME]      VARCHAR (20)  NOT NULL,
    [DEPARTMENT]     NUMERIC (3)   NOT NULL,
    [MUNICIPIO]      VARCHAR (2)   NULL,
    [DOMAIN]         VARCHAR (15)  DEFAULT ('ANAG') NOT NULL,
    [COGNOME]        VARCHAR (100) NULL,
    [NOME]           VARCHAR (100) NULL,
    [ROLE]           VARCHAR (1)   DEFAULT ('0') NOT NULL,
    [CODICE_FISCALE] VARCHAR (16)  NULL,
    CONSTRAINT [USERS_BACKEND_PK] PRIMARY KEY CLUSTERED ([ID_USER] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [USERS_BACKEND_INDEX1]
    ON [FAXPEC].[MAIL_USERS_BACKEND]([USER_NAME] ASC, [DEPARTMENT] ASC);


GO
ALTER INDEX [USERS_BACKEND_INDEX1]
    ON [FAXPEC].[MAIL_USERS_BACKEND] DISABLE;


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$MAIL_USERS_BACKEND]
   ON [FAXPEC].[MAIL_USERS_BACKEND]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE              
               @new$ID_USER numeric(10, 0), 
               @new$USER_NAME varchar(20), 
               @new$DEPARTMENT numeric(3, 0), 
               @new$MUNICIPIO varchar(2), 
               @new$DOMAIN varchar(15), 
               @new$COGNOME varchar(100), 
               @new$NOME varchar(100), 
               @new$ROLE varchar(1), 
               @new$CODICE_FISCALE varchar(16)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT                    
                     ID_USER, 
                     USER_NAME, 
                     DEPARTMENT, 
                     MUNICIPIO, 
                     DOMAIN, 
                     COGNOME, 
                     NOME, 
                     ROLE, 
                     CODICE_FISCALE
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                
                  @new$ID_USER, 
                  @new$USER_NAME, 
                  @new$DEPARTMENT, 
                  @new$MUNICIPIO, 
                  @new$DOMAIN, 
                  @new$COGNOME, 
                  @new$NOME, 
                  @new$ROLE, 
                  @new$CODICE_FISCALE

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN
                        IF @triggerType = 'I'
                           BEGIN                             
                                 SELECT @new$ID_USER = NEXT VALUE FOR FAXPEC.USER_BACKEND_SEQ
                           END
                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.MAIL_USERS_BACKEND(                    
                     ID_USER, 
                     USER_NAME, 
                     DEPARTMENT, 
                     MUNICIPIO, 
                     DOMAIN, 
                     COGNOME, 
                     NOME, 
                     ROLE, 
                     CODICE_FISCALE)
                     VALUES (                       
                        @new$ID_USER, 
                        @new$USER_NAME, 
                        @new$DEPARTMENT, 
                        @new$MUNICIPIO, 
                        @new$DOMAIN, 
                        @new$COGNOME, 
                        @new$NOME, 
                        @new$ROLE, 
                        @new$CODICE_FISCALE)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                       
                        @new$ID_USER, 
                        @new$USER_NAME, 
                        @new$DEPARTMENT, 
                        @new$MUNICIPIO, 
                        @new$DOMAIN, 
                        @new$COGNOME, 
                        @new$NOME, 
                        @new$ROLE, 
                        @new$CODICE_FISCALE

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.USERS_BACKEND_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'INDEX', @level2name = N'USERS_BACKEND_INDEX1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.ID_USER', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'ID_USER';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.USER_NAME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'USER_NAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.DEPARTMENT', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'DEPARTMENT';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.MUNICIPIO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'MUNICIPIO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.DOMAIN', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'DOMAIN';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.COGNOME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'COGNOME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.NOME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'NOME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.ROLE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'ROLE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.CODICE_FISCALE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'COLUMN', @level2name = N'CODICE_FISCALE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_USERS_BACKEND.USERS_BACKEND_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'MAIL_USERS_BACKEND', @level2type = N'CONSTRAINT', @level2name = N'USERS_BACKEND_PK';

