CREATE TABLE [FAXPEC].[ROLES] (
    [ID]   VARCHAR (45) NOT NULL,
    [NAME] VARCHAR (45) NULL,
    CONSTRAINT [PK_ROLES_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$ROLES]
   ON [FAXPEC].[ROLES]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE            
               @new$ID varchar(45), 
               @new$NAME varchar(45)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT ID, NAME
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO @new$ID, @new$NAME

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN

                        COLUMN_SEQUENCES:

                        BEGIN
                           IF @triggerType = 'I' 
                              SELECT @new$ID = NEXT VALUE FOR FAXPEC.ROLES_SEQ
                        END

                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.ROLES(ID, NAME)
                     VALUES ( @new$ID, @new$NAME)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO @new$ID, @new$NAME

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.ROLES.PK_ROLES_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'ROLES', @level2type = N'CONSTRAINT', @level2name = N'PK_ROLES_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.ROLES', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'ROLES';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.ROLES.ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'ROLES', @level2type = N'COLUMN', @level2name = N'ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.ROLES."NAME"', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'ROLES', @level2type = N'COLUMN', @level2name = N'NAME';

