CREATE TABLE [FAXPEC].[RUBR_ENTITA] (
    [ID_REFERRAL]     NUMERIC (10)    NOT NULL,
    [ID_PADRE]        NUMERIC (10)    NULL,
    [REFERRAL_TYPE]   VARCHAR (20)    NULL,
    [COGNOME]         NVARCHAR (200)  NULL,
    [NOME]            NVARCHAR (100)  NULL,
    [COD_FIS]         VARCHAR (16)    NULL,
    [P_IVA]           VARCHAR (11)    NULL,
    [RAGIONE_SOCIALE] NVARCHAR (100)  NULL,
    [UFFICIO]         NVARCHAR (1000) NULL,
    [NOTE]            NVARCHAR (200)  NULL,
    [REF_ID_ADDRESS]  NUMERIC (10)    NULL,
    [FLG_IPA]         VARCHAR (1)     DEFAULT ((0)) NULL,
    [IPA_DN]          NVARCHAR (200)  NULL,
    [IPA_ID]          VARCHAR (30)    NULL,
    [DISAMB_PRE]      NVARCHAR (100)  NULL,
    [DISAMB_POST]     NVARCHAR (100)  NULL,
    [REF_ORG]         NUMERIC (10)    NULL,
    [SITO_WEB]        NVARCHAR (200)  NULL,
    [AFF_IPA]         NUMERIC (3)     NULL,
    CONSTRAINT [RUBR_ENTITA_PK] PRIMARY KEY CLUSTERED ([ID_REFERRAL] ASC),
    CONSTRAINT [RUBR_ENTITA_RUBR_ADDRESS_FK1] FOREIGN KEY ([REF_ID_ADDRESS]) REFERENCES [FAXPEC].[RUBR_ADDRESS] ([ID_ADDRESS]),
    CONSTRAINT [RUBR_ENTITA_RUBR_ENTITA_FK1] FOREIGN KEY ([ID_PADRE]) REFERENCES [FAXPEC].[RUBR_ENTITA] ([ID_REFERRAL]),
    CONSTRAINT [RUBR_ENTITA_RUBR_REFERRAL_FK1] FOREIGN KEY ([REFERRAL_TYPE]) REFERENCES [FAXPEC].[RUBR_REFERRAL_TYPE] ([REFERRAL_TYPE])
);


GO
CREATE NONCLUSTERED INDEX [RUBR_ENTITA_INDEX1]
    ON [FAXPEC].[RUBR_ENTITA]([ID_PADRE] ASC);


GO
ALTER INDEX [RUBR_ENTITA_INDEX1]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO
CREATE NONCLUSTERED INDEX [RUBR_ENTITA_INDEX2]
    ON [FAXPEC].[RUBR_ENTITA]([COGNOME] ASC, [NOME] ASC);


GO
ALTER INDEX [RUBR_ENTITA_INDEX2]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO
CREATE NONCLUSTERED INDEX [RUBR_ENTITA_INDEX3]
    ON [FAXPEC].[RUBR_ENTITA]([COD_FIS] ASC);


GO
ALTER INDEX [RUBR_ENTITA_INDEX3]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO
CREATE NONCLUSTERED INDEX [RUBR_ENTITA_INDEX4]
    ON [FAXPEC].[RUBR_ENTITA]([REF_ID_ADDRESS] ASC);


GO
ALTER INDEX [RUBR_ENTITA_INDEX4]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO
CREATE NONCLUSTERED INDEX [RUBR_ENTITA_INDEX5]
    ON [FAXPEC].[RUBR_ENTITA]([IPA_DN] ASC);


GO
ALTER INDEX [RUBR_ENTITA_INDEX5]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO
CREATE NONCLUSTERED INDEX [RUBR_ENTITA_INDEX6]
    ON [FAXPEC].[RUBR_ENTITA]([RAGIONE_SOCIALE] ASC);


GO
ALTER INDEX [RUBR_ENTITA_INDEX6]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO
CREATE UNIQUE NONCLUSTERED INDEX [RUBR_ENTITA_INDEX7]
    ON [FAXPEC].[RUBR_ENTITA]([P_IVA] ASC);


GO
ALTER INDEX [RUBR_ENTITA_INDEX7]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO
CREATE NONCLUSTERED INDEX [TIPO_ENTITA_INDEX]
    ON [FAXPEC].[RUBR_ENTITA]([REFERRAL_TYPE] ASC);


GO
ALTER INDEX [TIPO_ENTITA_INDEX]
    ON [FAXPEC].[RUBR_ENTITA] DISABLE;


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$RUBR_ENTITA]
   ON [FAXPEC].[RUBR_ENTITA]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE           
               @new$ID_REFERRAL numeric(10, 0), 
               @new$ID_PADRE numeric(10, 0), 
               @new$REFERRAL_TYPE varchar(20), 
               @new$COGNOME nvarchar(200), 
               @new$NOME nvarchar(100), 
               @new$COD_FIS varchar(16), 
               @new$P_IVA varchar(11), 
               @new$RAGIONE_SOCIALE nvarchar(100), 
               @new$UFFICIO nvarchar(1000), 
               @new$NOTE nvarchar(200), 
               @new$REF_ID_ADDRESS numeric(10, 0), 
               @new$FLG_IPA varchar(1), 
               @new$IPA_DN nvarchar(200), 
               @new$IPA_ID varchar(30), 
               @new$DISAMB_PRE nvarchar(100), 
               @new$DISAMB_POST nvarchar(100), 
               @new$REF_ORG numeric(10, 0), 
               @new$SITO_WEB nvarchar(200), 
               @new$AFF_IPA numeric(3, 0)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT                     
                     ID_REFERRAL, 
                     ID_PADRE, 
                     REFERRAL_TYPE, 
                     COGNOME, 
                     NOME, 
                     COD_FIS, 
                     P_IVA, 
                     RAGIONE_SOCIALE, 
                     UFFICIO, 
                     NOTE, 
                     REF_ID_ADDRESS, 
                     FLG_IPA, 
                     IPA_DN, 
                     IPA_ID, 
                     DISAMB_PRE, 
                     DISAMB_POST, 
                     REF_ORG, 
                     SITO_WEB, 
                     AFF_IPA
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                
                  @new$ID_REFERRAL, 
                  @new$ID_PADRE, 
                  @new$REFERRAL_TYPE, 
                  @new$COGNOME, 
                  @new$NOME, 
                  @new$COD_FIS, 
                  @new$P_IVA, 
                  @new$RAGIONE_SOCIALE, 
                  @new$UFFICIO, 
                  @new$NOTE, 
                  @new$REF_ID_ADDRESS, 
                  @new$FLG_IPA, 
                  @new$IPA_DN, 
                  @new$IPA_ID, 
                  @new$DISAMB_PRE, 
                  @new$DISAMB_POST, 
                  @new$REF_ORG, 
                  @new$SITO_WEB, 
                  @new$AFF_IPA

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN
                        IF @triggerType = 'I'
                           BEGIN                            
                                 SELECT @new$ID_REFERRAL = NEXT VALUE FOR FAXPEC.RUBR_CONTATTI_SEQ
                           END
                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.RUBR_ENTITA(                  
                     ID_REFERRAL, 
                     ID_PADRE, 
                     REFERRAL_TYPE, 
                     COGNOME, 
                     NOME, 
                     COD_FIS, 
                     P_IVA, 
                     RAGIONE_SOCIALE, 
                     UFFICIO, 
                     NOTE, 
                     REF_ID_ADDRESS, 
                     FLG_IPA, 
                     IPA_DN, 
                     IPA_ID, 
                     DISAMB_PRE, 
                     DISAMB_POST, 
                     REF_ORG, 
                     SITO_WEB, 
                     AFF_IPA)
                     VALUES (                       
                        @new$ID_REFERRAL, 
                        @new$ID_PADRE, 
                        @new$REFERRAL_TYPE, 
                        @new$COGNOME, 
                        @new$NOME, 
                        @new$COD_FIS, 
                        @new$P_IVA, 
                        @new$RAGIONE_SOCIALE, 
                        @new$UFFICIO, 
                        @new$NOTE, 
                        @new$REF_ID_ADDRESS, 
                        @new$FLG_IPA, 
                        @new$IPA_DN, 
                        @new$IPA_ID, 
                        @new$DISAMB_PRE, 
                        @new$DISAMB_POST, 
                        @new$REF_ORG, 
                        @new$SITO_WEB, 
                        @new$AFF_IPA)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                      
                        @new$ID_REFERRAL, 
                        @new$ID_PADRE, 
                        @new$REFERRAL_TYPE, 
                        @new$COGNOME, 
                        @new$NOME, 
                        @new$COD_FIS, 
                        @new$P_IVA, 
                        @new$RAGIONE_SOCIALE, 
                        @new$UFFICIO, 
                        @new$NOTE, 
                        @new$REF_ID_ADDRESS, 
                        @new$FLG_IPA, 
                        @new$IPA_DN, 
                        @new$IPA_ID, 
                        @new$DISAMB_PRE, 
                        @new$DISAMB_POST, 
                        @new$REF_ORG, 
                        @new$SITO_WEB, 
                        @new$AFF_IPA

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_INDEX1', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'RUBR_ENTITA_INDEX1';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_INDEX2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'RUBR_ENTITA_INDEX2';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_INDEX3', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'RUBR_ENTITA_INDEX3';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_INDEX4', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'RUBR_ENTITA_INDEX4';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_INDEX5', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'RUBR_ENTITA_INDEX5';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_INDEX6', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'RUBR_ENTITA_INDEX6';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_INDEX7', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'RUBR_ENTITA_INDEX7';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.TIPO_ENTITA_INDEX', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'INDEX', @level2name = N'TIPO_ENTITA_INDEX';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.ID_REFERRAL', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'ID_REFERRAL';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.ID_PADRE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'ID_PADRE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.REFERRAL_TYPE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'REFERRAL_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.COGNOME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'COGNOME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.NOME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'NOME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.COD_FIS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'COD_FIS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.P_IVA', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'P_IVA';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RAGIONE_SOCIALE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'RAGIONE_SOCIALE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.UFFICIO', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'UFFICIO';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.NOTE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'NOTE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.REF_ID_ADDRESS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'REF_ID_ADDRESS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.FLG_IPA', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'FLG_IPA';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.IPA_DN', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'IPA_DN';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.IPA_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'IPA_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.DISAMB_PRE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'DISAMB_PRE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.DISAMB_POST', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'DISAMB_POST';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.REF_ORG', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'REF_ORG';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.SITO_WEB', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'SITO_WEB';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.AFF_IPA', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'COLUMN', @level2name = N'AFF_IPA';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_ENTITA.RUBR_ENTITA_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_ENTITA', @level2type = N'CONSTRAINT', @level2name = N'RUBR_ENTITA_PK';

