CREATE TABLE [FAXPEC].[RUBR_REFERRAL_TYPE_TAGS] (
    [REF_REFERRAL_TYPE] VARCHAR (20) NOT NULL,
    [REF_ID_TAG]        NUMERIC (10) NOT NULL,
    CONSTRAINT [RUBR_REFERRAL_TYPE_TAGS_PK] PRIMARY KEY CLUSTERED ([REF_REFERRAL_TYPE] ASC, [REF_ID_TAG] ASC),
    CONSTRAINT [RUBR_REFERRAL_TYPE_TAGS_R_FK1] FOREIGN KEY ([REF_REFERRAL_TYPE]) REFERENCES [FAXPEC].[RUBR_REFERRAL_TYPE] ([REFERRAL_TYPE]),
    CONSTRAINT [RUBR_REFERRAL_TYPE_TAGS_R_FK2] FOREIGN KEY ([REF_ID_TAG]) REFERENCES [FAXPEC].[RUBR_TAGS] ([ID_TAG])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_REFERRAL_TYPE_TAGS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_REFERRAL_TYPE_TAGS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_REFERRAL_TYPE_TAGS.REF_REFERRAL_TYPE', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_REFERRAL_TYPE_TAGS', @level2type = N'COLUMN', @level2name = N'REF_REFERRAL_TYPE';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_REFERRAL_TYPE_TAGS.REF_ID_TAG', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_REFERRAL_TYPE_TAGS', @level2type = N'COLUMN', @level2name = N'REF_ID_TAG';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_REFERRAL_TYPE_TAGS.RUBR_REFERRAL_TYPE_TAGS_PK', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_REFERRAL_TYPE_TAGS', @level2type = N'CONSTRAINT', @level2name = N'RUBR_REFERRAL_TYPE_TAGS_PK';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_REFERRAL_TYPE_TAGS.RUBR_REFERRAL_TYPE_TAGS_R_FK2', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'RUBR_REFERRAL_TYPE_TAGS', @level2type = N'CONSTRAINT', @level2name = N'RUBR_REFERRAL_TYPE_TAGS_R_FK2';

