CREATE TABLE [FAXPEC].[USERS] (
    [ID]            VARCHAR (45)  NOT NULL,
    [USERNAME]      VARCHAR (45)  NULL,
    [PASSWORDHASH]  VARCHAR (100) NULL,
    [SECURITYSTAMP] VARCHAR (45)  NULL,
    CONSTRAINT [PK_USERS_ID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CK_USERS_USERNAME] UNIQUE NONCLUSTERED ([USERNAME] ASC)
);


GO

CREATE TRIGGER [FAXPEC].[InsteadOfInsertOn$USERS]
   ON [FAXPEC].[USERS]
    INSTEAD OF INSERT
      AS 
         /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
         BEGIN

            SET  NOCOUNT  ON

            DECLARE
               @triggerType char(1)

            SELECT @triggerType = 'I'

            /* column variables declaration*/
            DECLARE             
               @new$ID varchar(45), 
               @new$USERNAME varchar(45), 
               @new$PASSWORDHASH varchar(100), 
               @new$SECURITYSTAMP varchar(45)

            DECLARE
                ForEachInsertedRowTriggerCursor CURSOR LOCAL FORWARD_ONLY READ_ONLY FOR 
                  SELECT                  
                     ID, 
                     USERNAME, 
                     PASSWORDHASH, 
                     SECURITYSTAMP
                  FROM inserted

            OPEN ForEachInsertedRowTriggerCursor

            FETCH ForEachInsertedRowTriggerCursor
                INTO                
                  @new$ID, 
                  @new$USERNAME, 
                  @new$PASSWORDHASH, 
                  @new$SECURITYSTAMP

            WHILE @@fetch_status = 0
            
               BEGIN

                  /* row-level triggers implementation: begin*/
                  BEGIN
                     BEGIN

                        COLUMN_SEQUENCES:

                        BEGIN
                           IF @triggerType = 'I' 
                              SELECT @new$ID = NEXT VALUE FOR FAXPEC.USERS_SEQ
                        END

                     END
                  END
                  /* row-level triggers implementation: end*/

                  /* DML-operation emulation*/
                  INSERT FAXPEC.USERS(                  
                     ID, 
                     USERNAME, 
                     PASSWORDHASH, 
                     SECURITYSTAMP)
                     VALUES (                      
                        @new$ID, 
                        @new$USERNAME, 
                        @new$PASSWORDHASH, 
                        @new$SECURITYSTAMP)

                  FETCH ForEachInsertedRowTriggerCursor
                      INTO                   
                        @new$ID, 
                        @new$USERNAME, 
                        @new$PASSWORDHASH, 
                        @new$SECURITYSTAMP

               END

            CLOSE ForEachInsertedRowTriggerCursor

            DEALLOCATE ForEachInsertedRowTriggerCursor

         END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.USERS.PK_USERS_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'USERS', @level2type = N'CONSTRAINT', @level2name = N'PK_USERS_ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.USERS', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'USERS';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.USERS.ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'USERS', @level2type = N'COLUMN', @level2name = N'ID';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.USERS.USERNAME', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'USERS', @level2type = N'COLUMN', @level2name = N'USERNAME';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.USERS.PASSWORDHASH', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'USERS', @level2type = N'COLUMN', @level2name = N'PASSWORDHASH';


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.USERS.SECURITYSTAMP', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'TABLE', @level1name = N'USERS', @level2type = N'COLUMN', @level2name = N'SECURITYSTAMP';

