CREATE SEQUENCE [FAXPEC].[COMUNICAZIONI_TITOLI_SEQ]
    AS NUMERIC (28)
    START WITH 21
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999
    NO CACHE;


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.COMUNICAZIONI_TITOLI_SEQ', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'SEQUENCE', @level1name = N'COMUNICAZIONI_TITOLI_SEQ';

