CREATE SEQUENCE [FAXPEC].[MAIL_SERVER_SEQ]
    AS NUMERIC (28)
    START WITH 4
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 999999999
    CACHE 20;


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.MAIL_SERVER_SEQ', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'SEQUENCE', @level1name = N'MAIL_SERVER_SEQ';

