CREATE SEQUENCE [FAXPEC].[RUBR_CONTATTI_BACKEND_SEQ]
    AS NUMERIC (28)
    START WITH 130800
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999
    NO CACHE;


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.RUBR_CONTATTI_BACKEND_SEQ', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'SEQUENCE', @level1name = N'RUBR_CONTATTI_BACKEND_SEQ';

