CREATE SEQUENCE [FAXPEC].[SEQ_USERCLAIMS_ID]
    AS NUMERIC (28)
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9999999999
    CACHE 20;


GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.SEQ_USERCLAIMS_ID', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'SEQUENCE', @level1name = N'SEQ_USERCLAIMS_ID';

