
CREATE PROCEDURE FAXPEC.VERIFY_MAPPING  
   @P_APP_CODE varchar(max),
   @P_CODE_COMUNE varchar(max),
   @P_RESPONSE varchar(max)  OUTPUT
AS 
   /*Generated by SQL Server Migration Assistant for Oracle version 7.3.0.*/
   BEGIN

      DECLARE
         @V_ID_TITOLO numeric(10, 0) = -1, 
         @V_ID_BACKEND numeric(10, 0) = -1, 
         @V_ID_CONTATTO numeric(10, 0) = -1, 
         @V_MAIL nvarchar(100) = NULL

      BEGIN TRY

         SET @P_RESPONSE = NULL

         SET @P_RESPONSE = NULL

         BEGIN

            BEGIN TRY
               SELECT @V_ID_TITOLO = COMUNICAZIONI_TITOLI.ID_TITOLO
               FROM FAXPEC.COMUNICAZIONI_TITOLI
               WHERE COMUNICAZIONI_TITOLI.APP_CODE = @P_APP_CODE
            END TRY

            BEGIN CATCH
               BEGIN

                  SET @P_RESPONSE = 'ERROR: CODICE APPLICAZIONE ERRATO'

                  GOTO EXIT_CLOSE

               END
            END CATCH

         END

         BEGIN

            BEGIN TRY
               SELECT @V_ID_BACKEND = RUBR_BACKEND.ID_BACKEND
               FROM FAXPEC.RUBR_BACKEND
               WHERE RUBR_BACKEND.BACKEND_CODE = @P_CODE_COMUNE
            END TRY

            BEGIN CATCH
               BEGIN

                  SET @P_RESPONSE = 'ERROR: CODICE BACKEND NON PRESENTE'

                  GOTO EXIT_CLOSE

               END
            END CATCH

         END

         BEGIN

            BEGIN TRY

               SELECT @V_ID_CONTATTO = RUBR_CONTATTI_BACKEND.REF_ID_CONTATTO
               FROM FAXPEC.RUBR_CONTATTI_BACKEND
               WHERE 
                  RUBR_CONTATTI_BACKEND.REF_ID_CANALE = 1 AND 
                  RUBR_CONTATTI_BACKEND.REF_ID_BACKEND = @V_ID_BACKEND AND 
                  RUBR_CONTATTI_BACKEND.REF_ID_TITOLO = @V_ID_TITOLO

               IF @V_ID_CONTATTO IS NULL
                  RAISERROR(59999, 16, 1, N'ORA-01722%')

            END TRY

            BEGIN CATCH
               BEGIN

                  SET @P_RESPONSE = 'ERROR: CONTATTO NON ASSOCIATO'

                  GOTO EXIT_CLOSE

               END
            END CATCH

         END

         BEGIN

            BEGIN TRY

               SELECT @V_MAIL = RUBR_CONTATTI.MAIL
               FROM FAXPEC.RUBR_CONTATTI
               WHERE RUBR_CONTATTI.ID_CONTACT = @V_ID_CONTATTO

               IF @V_MAIL IS NULL OR ssma_oracle.trim2_nvarchar(3, @V_MAIL) = NULL
                  BEGIN

                     SET @P_RESPONSE = 'ERROR: IL CONTATTO NON HA UN INDIRIZZO MAIL'

                     GOTO EXIT_CLOSE

                  END

               SET @P_RESPONSE = 'MAIL: ' + ISNULL(@V_MAIL, '')

            END TRY

            BEGIN CATCH
               BEGIN

                  SET @P_RESPONSE = 'ERROR: CONTATTO INESISTENTE'

                  GOTO EXIT_CLOSE

               END
            END CATCH

         END

         EXIT_CLOSE:

         SET @V_ID_TITOLO = -1

         SET @V_ID_BACKEND = -1

         SET @V_ID_CONTATTO = -1

         SET @V_MAIL = NULL

      END TRY

      BEGIN CATCH
         BEGIN
            SET @P_RESPONSE = 'ERROR: ECCEZIONE NELLA STORED PROCEDURE'
         END
      END CATCH

   END

GO
EXECUTE sp_addextendedproperty @name = N'MS_SSMA_SOURCE', @value = N'FAXPEC.VERIFY_MAPPING', @level0type = N'SCHEMA', @level0name = N'FAXPEC', @level1type = N'PROCEDURE', @level1name = N'VERIFY_MAPPING';

